### ISSUE TITLE
Lawful, Unlawful, and Chaotic: are there more intuitive names?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1005]
The names of these three modules in our `characters` package are a little odd for sure, but they are reasonably descriptive of what a reader can expect to find therein.

But are there names to make it more intuitive for those giving a cursory glance?

@ravital asks: does it make more sense to use "honest", "malicious" and "semi-malicious"?

Are there other candidate names that are, for whatever reason, preferable?

**Comment by jMyles** [comment]
For my part, I think that borrowing from the alignment traditions of role-playing games make great sense.  The distinction between these three specific terms dates at least to the mid-70s, when Dungeons and Dragons [adopted them](https://en.wikipedia.org/wiki/Alignment_(Dungeons_%26_Dragons)).

A large part of my resistance to using the terms "honest" and "dishonest" or "malicious" is that these our Characters are not meant to be a mapping to users or processes on the network.  A User will sometimes invoke multiple Characters, and it's even possible that a Character can represent no User at all.  Honesty, dishonesty, and malice are traits that are best understood in their descriptions of user activity rather than the logic of a discrete class.

Calling a class "honest" does little to explain to me exactly what I can expect for the methods of that class to have in common.  On the other hand, "lawful" is well-defined: it tells me that the methods of that class obey the laws of the network.  If the laws are written well (ie, the protocol is cognizable given the ecosystem in which the network is deployed), then we expect lawful methods to be the most reward, and thus that *all* users (not just honest ones) to use lawful Characters.

The distinction between "chaotic" and "semi-malicious" is particularly striking: there is nothing even "semi-malicious" about the chaotic impetus that we have in the current chaotic Characters, nor those that are easy to envision.  Instead, the distinction is that the logic we write in the methods of chaotic characters work without any regard at all to the network protocol, and instead are useful by dint of their logic alone.

A brief aside on the moral commentary inherent in this terminology:  The traditional alignment structure of RPGs includes two axes: one of morality (good, neutral, evil) and one of legality (lawful, unlawful, chaotic).  Our Characters are not organized in any sense by the former; only by the latter.  Some traditional cryptography literature uses the term "malicious" - a term with unambiguous moral implications - to describe actions that are actually better understood as stemming from the legal axis rather than the moral axis.  In other words, I think that RPG lore gets this right where cryptography literature gets it wrong.

**Comment by cygnusv** [comment]
My 2 cents:
* Just for context, I've been reviewing some [alignment charts for movies, books, etc.](https://www.google.com/search?q=alignment+chart&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiHs9DJsbXiAhWqAmMBHU36CZ4Q_AUIDigB&biw=1440&bih=651). They all suck. Which makes me kind of sceptical wrt to this whole categorization system.
* I'd strongly prefer to have at least Alice, Bob and Ursula having their own separate modules, something like `nucypher.characters.alice.py` (related: https://github.com/nucypher/nucypher/issues/367). How's even possible that we have that for `nucypher.cli.characters.alice.py` and not the real Alice?
* Traditional actors in cryptographic literature labeled as "honest", "semi-honest", "malicious", etc. would be actually all be labeled as "lawful" by RPG players, since they all abide by the rules (e.g, what the hell is an "honest-but-curious" actor, right?). The rationale for that is that it doesn't have any sense to try to devise a cryptographic proof of security involving a chaotic, unpredictable character; it's impossible. I think that approach is not very useful either.
* We shouldn't spend time with this discussion anyway :P

**Comment by cygnusv** [comment]
What about closing this? Although I think there may be better names there, I'd prefer to keep the status quo and spend our time in other stuff.

**Comment by afrancht** [comment]
This is my opinion regarding the naming.

_My interpretation of lawful, unlawful and chaotic?_
What I understood by `lawful`, `unlawful` and `chaotic` is that in each file you have copies of all characters and that in the `unlawful` and `chaotic` one you give each character higher privileges to see what security errors/bugs may arise. Given that my cryptography knowledge comes from the literature I assumed that `lawful` meant benign, `unlawful` and `chaotic` meant malicious but the difference between `chaotic` and `unlawful` is not clear. 

**Naming**

_Problems with current naming_
* Usability issue - given that you have lawful and unlawful characters all in two single files, I could potentially be importing all my characters and use the unlawful version without realising. I know this is a silly typo, but this may save you many headaches in the future. 

_Opinion on already made arguments_
I disagree with the following:
> Characters are not meant to be a mapping to users or processes on the network. A User will sometimes invoke multiple Characters, and it's even possible that a Character can represent no User at all.
>

If a `character` cannot be mapped to a person or a process then it should probably not be named a "character". 

Up to now, all your characters can be mapped to a person:
* Alice is the data owner or data subject (in regulatory terms) thus they are a user.
* Ursula is a node that performs re-encryption but you could argue that he is a worker, like a locksmith that makes small changes to the lock of a vault.
* Bob is the data consumer, thus they are also a user.
* Enrico is in charge of encrypting the data, you can think of him as a doctor adding your blood analysis to your repository of medical data. 
* Felix is the person that gives me the tokens I need to use the NuCypher Network (as far as I know).

I disagree with the following:
>If the laws are written well (ie, the protocol is cognizable given the ecosystem in which the network is deployed), then we expect lawful methods to be the most reward, and thus that all users (not just honest ones) to use lawful Characters.
>

Something that is supposed to be intuitive should not have a premise in its definition. That means that for me to intuitively understand what rules are the characters following I have to know the rules, making it more difficult for me to understand the system as a whole. An intuitive approach should be something that helps me lead to a conclusion "I don't need to know or understand this because it's not relevant to what I'm trying to achieve"

**Character module organisation**

_Problems with current character module organisation_
* It is difficult for me to know what dependencies a certain character has since all modules are imported at the top of the file.
* Given that you have three different versions of these characters (lawful, unlawful and chaotic) having large codebases for each character makes it more difficult for me to isolate the code for each and compare.
* A non-segmented code base is less maintainable and more difficult to understand.

_My opinion on already made arguments_
I agree with the following:
> I'd strongly prefer to have at least Alice, Bob and Ursula having their own separate modules
> 

In your documentation, you have done a great job at differentiating between the roles and responsibilities of characters concisely and succinctly, but when someone wants to understand the actual code, they have to tackle all the characters at once. Jumping around lines. I guess this increases pain for someone to use the NuCypher network, makes it less maintainable and more difficult for new hires to understand. 

Conclusion - TLDR:
* It's better to understand the intent of the character rather than the "following of the rules", especially since I don't know the rules.
* If you use the current naming then there should be a clear explanation of what the rules are and especially of the difference between `unlawful` and `chaotic` (which there might be, again I'm an outsider so don't know about every piece of documentation).
* Less "hidden" meaning for people to understand if it follows traditional cryptography literature.
* Files similar in name and functionality that result in a security risk should not be in the same folder.
* I think there should be a file per character.

Again, this is only my opinion! I don't think this is critical at this stage but important when generating traction.
