### ISSUE TITLE
Is using contextlib.suppress in non-test code an antipattern?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#1032]
A few times over the past few days, @KPrasch has objected to using `contextlib.suppress` to abort blocks of code where an exception is used as a continuation signal.  For example, checking to see if a node is already known:

```
            # First, determine if this is an outdated representation of an already known node.
            with suppress(KeyError):
                already_known_node = self.known_nodes[node.checksum_public_address]
                if not node.timestamp > already_known_node.timestamp:
                    self.log.debug("Skipping already known node {}".format(already_known_node))
                    # This node is already known.  We can safely continue to the next.
                    continue
```

@KPrasch says that he understands this to be widely regarded as an antipattern.  I think it's an elegant approach; I much prefer entering the block this way - using the context manager to carve out the block which will abort - than to use an `if` to pre-check the condition before entering the block.

Additionally, after a few minutes of searching, I cannot find any objections to this pattern in the community.  If good, well-thought-out objections exist, I'm open-minded about changing my view on this.

**Comment by cygnusv** [comment]
```python
# First, determine if this is an outdated representation of an already known node.
if self.known_nodes in node.checksum_public_address
    already_known_node = self.known_nodes[node.checksum_public_address]
    if not node.timestamp > already_known_node.timestamp:
        self.log.debug("Skipping already known node {}".format(already_known_node))
        # This node is already known.  We can safely continue to the next.
        continue
```

**Comment by jMyles** [comment]
`if self.known_nodes in node.checksum_public_address`

wut

I assume you meant:

`if node in self.known_nodes:`

...but how is that preferable?

**Comment by cygnusv** [comment]
I'm currently debugging something and I've hit this precise block of code and I couldn't understand it right away. I had to look again what `supress` does. 

> `if node in self.known_nodes:`
> 
> ...but how is that preferable?

...because it reads naturally? I bet my grandma would understand this faster that way than `with suppress(KeyError)`. And she doesn't speak English.

@jMyles I don't understand how the `suppress` can be preferable for you. I think `with suppress(some_exception)` can be better when trying to come up with a conditional expression to avoid the exception ends up in a rather complex/confusing code. But c'mon, man, in this case, the conditional expression is plain English:`if node in self.known_nodes`

**Comment by tuxxy** [comment]
There's no way to fix this without starting some sort of holy war.

Or we use a walrus.
