### ISSUE TITLE
Make sample selection buffer configurable

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1061]
See: <https://github.com/nucypher/nucypher/pull/984/files#diff-5b3bd97d75d539a8b1311b82d491cb58R119>

**Comment by KPrasch** [comment]
@fjarri - Considering `WeightedSampler`'s design, what do you think about exposing any part sample selection to user configuration / CLI flag, or instead closing this issue?

**Comment by fjarri** [comment]
If I understand correctly, the analogous logic is now contained in `policies.py::PrefetchStrategy`. I don't think we need to make it configurable right now, since with the parallel proposals it is stable enough as it is, as long as a significant part of nodes is available. Here is a simple simulation for 2000 total nodes, assuming a proposal takes 1s and the timeout is 20s:

`n=3`:
![t_3](https://user-images.githubusercontent.com/30720/109410439-97bc2800-794f-11eb-9f8a-605e09c4ae67.png)

`n=5`:
![t_5](https://user-images.githubusercontent.com/30720/109410441-9c80dc00-794f-11eb-941c-8ca094e62ec5.png)

(code: https://gist.github.com/fjarri/e8584987e40477108b83de5e48dad763)
