### ISSUE TITLE
Refactor Vladimir to consider Worker / Staker Separation

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1075]
WIP

**Comment by cygnusv** [comment]
The Worker/Staker separation has introduced a lot of changes to the traditional attacks that Vladimir could perform. Instead of trying to just fix/adapt the tests, I think we may need to come up with a whole new battery of Vladimir scenarios. 

This is the type of situation where I lean towards borrowing another brain, not involved in the recent development. I'd like to summon @jMyles for this (he's always been a great advocate of our friend Vlad), although anyone with a fresh, out-of-the box viewpoint is of course welcome for this.
