### ISSUE TITLE
`nucypher ursula` in sekanjabin expects only contract_registry.json, never dev_contract_registry.json

### ISSUE THREAD

**Issue by michwill** [nucypher/nucypher#1161]
Specifying --dev option causes Ursula to look for the contract registry in `/tmp`.

Temporary solution: `ln -s ~/.local/share/nucypher/dev_contract_registry.json ~/.local/share/nucypher/contract_registry.json`

**Comment by KPrasch** [comment]
At the moment a better way to handle this is to pass `--registry-filepath` to your nucypher command. 

What you've experienced here is a developer experience issue in my opinion:

The default deployment registry filepath is always used when running `nucypher-deploy` commands unless `--dev` is passed, then `dev_contract_registry.json` is used instead of `contract_registry.json`.  

Conversely, when running `nucypher stake` commands, chainID determines which registry filepath to use.

I think we can make a more streamlined, informed, and unified experience here.

**Comment by michwill** [comment]
Yes, I am currently specifying --registry filepath indeed

**Comment by KPrasch** [comment]
I think this has been mostly solved when we made the the switch to in-memory registries by default and the rest is wont-fix.  

Specifying a registry via flag takes precedence over the memory one, so, If you want to use the registry generated by `nucypher-deploy --dev ..` (`dev_contract_registry.json`), then you must pass the absolute path to `--registry-filepath /path/to/dev_contract_registry.json`.

In broader terms, the usage of `--dev` for decentralized nodes is not well supported at this time.
