### ISSUE TITLE
Clearer error messages when creating duplicate policy with the same Bob + label

### ISSUE THREAD

**Issue by mswilkison** [nucypher/nucypher#1223]
When Alice tries to create a duplicate policy (same Bob and label) this fails at the smart contract level but works in Python. So we get unclear error messages: https://gist.github.com/mswilkison/e9b89ea373659ef4016adf03904db0f6

**Comment by jMyles** [comment]
I'm uhh, actually surprised this fails at all.  How does the smart contract know that a Policy already exists for this Bob?

**Comment by cygnusv** [comment]
Because the policyID in the Smart Contract is the first 16 bytes of the HRAC, which will be the same when using same bob + label.

**Comment by jMyles** [comment]
Got it.  I don't know if I knew we were using the HRAC for that.  But that's good; very sensible.

So I think, bigger picture, we don't want to assume that a given Alice has, in memory, a representation of which Policies have already been deployed.  Right?  So it makes sense to examine the condition on-chain in order to raise a more coherent message.

**Comment by cygnusv** [comment]
Yes, we don't have to assume it, although we kind of need it for other things (https://github.com/nucypher/nucypher/issues/875). In any case, what you say is one of the goals of the `horchata` EPIC (https://github.com/nucypher/nucypher/pull/1218): more pre- and post-transaction checks.

**Comment by cygnusv** [comment]
This problem has been recently hit by ourselves and others trying to grant on mainnet and IBEX testnet. 
A simple pre-transaction check would do to solve this issue.

**Comment by cygnusv** [comment]
Superseded by #2443
