### ISSUE TITLE
Make sure we support Policy authors to be smart contracts

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1406]
Let's say there's a DApp that want to reduce UX friction for Alice, abstracting the need for ETH funding to participate in NuCypher as policy authors. For example, this DApp can accept whatever payment is better for Alices and act as a proxy to the NuCypher Network.

In an eye-opening discussion with @szotov, he points out that this can be done by the DApp by setting up a contract acting as the policy author. Since Alice's ETH key is not tied anyway with her cryptographic keys (i.e, signing, encryption, delegation), it seems that in principle this approach has a lot of sense for this use case.

On the other hand, this type of use case doesn't feel like something we should implement in our code base – in other words, it's not our problem. Except that if we want to increase traction, then we should make sure that it's doable, even if we don't do it.

The question is: is there something in the codebase preventing this use case from being possible? 

Pinging @afrancht for the original discussion that led to this issue.

**Comment by afrancht** [comment]
I think that @cygnusv is right in stating that this is not something that NuCypher should implement but should make sure it is possible. 

Here is a small diagram of how I would see it implemented:
![NuCypher with a Policy Manager](https://user-images.githubusercontent.com/19917183/66505000-5b6dfa80-eac2-11e9-92da-a7555d8d1b37.png)

### Why NuCypher shouldn't implement it
In the context of the NuCypher network (as I understand it), it makes sense that each Alice takes care of their policies. This is because proxy re-encryption empowers "the user that has something to lose" (their plaintext/secret) to revoke a policy whenever she sees fit. Therefore, it would contradict your narrative as having a policy manager "out of context" introduces the issue of Alice having to trust the policy manager to create the policy right and with your current narrative, it is clear that this is not the case. 

Additionally, "the Policy Manager" abstracts the user away from managing policies for the sake of a better UX and UX varies from implementation to implementation thus creating one solution to fit all may not be possible. Example: in my implementation, I perhaps do not want to use the nucypher keyring and I want to provide the keys myself (as a user may make use of the NuCypher network from different devices). With the policy manager it would be a bit similar if how you create the policy is somewhat different to what I need, I will find myself writing my policy manager anyways.   

DISCLAIMER: I am not 100% sure I can use the NuCypher network without using the NuCypher keyring. I know that is possible with Umbral as you can provide a key as a parameter but if not that would also be a possible feature that increases usability and traction. 

### Why it should be possible
I think it should be possible because it allows non-tech-savvy users to make use of the NuCypher network without even knowing thus increasing your traction and "indirect" customer pool. For instance, in my project, we are looking to create a secure data store that benefits from the properties that the NuCypher provides aside from just the Cryptographic properties Umbral provides but don't necessarily want every user to have a wallet with ETH. 

My thought process is a bit like this: 

What the user wants to accomplish: securely store data on the cloud and ensure that I can share it with people according to a policy. 

and to accomplish that they have to:
1. Know what cryptocurrencies are.
2. Understand that there's a technology behind it.
3. Basic notions of cryptographic private and public keys.
4. Understand what a wallet is and have one.
5. Buy ETH (which implies perform KYC/banking approval in some wallets) -> also implies "staking some ETH" as it is a less liquid asset than cash.
6. Create an account on my platform.
7. Create a policy 
8. Upload the data.

With this proposed feature, they have to: 
1. Create an account on my platform.
2. Create a policy 
3. Upload the data.

And it is my problem to ensure that I am capturing enough value form my customers to purchase ETH to perform re-encryptions and to ensure that I don't run out of ETH.

### Is it currently possible?
I am currently investigating it as this is a crucial feature in the decision to use the NuCypher Network going forward or using Umbral by itself.

**Comment by jMyles** [comment]
This is a better stated rendition of #1275.  I'll close that and point here.

**Comment by ravital** [comment]
I think this is related but asking a broader question than #1275 was - we're no longer suggesting that _we_ should implement that functionality but rather if it's _possible_ given our codebase.  I agree with @cygnusv that for traction it's necessary to make sure that other actors (or SCs) can act as policy authors but (similar to my view on #1275) don't see any reason for us to implement this before mainnet (if we even do so at all).

**Comment by cygnusv** [comment]
@vzotova Is this closed by #1492?

**Comment by vzotova** [comment]
I think yes, at least should be
