### ISSUE TITLE
Build an auto-updater

### ISSUE THREAD

**Issue by tuxxy** [nucypher/nucypher#154]
NKMS _needs_ to ships with an auto-updater to ensure security and network updates are distributed to nodes efficiently.

I think this needs to be in with the mainnet release.

**Comment by jMyles** [comment]
:+1:

**Comment by jMyles** [comment]
Two years later: what's the state of the art in this area in decentralized networks?  Do we happen to know of anybody who is doing it in a way that we like?

I had not envisioned polling pypi (via `pip` or any other way).  I figured that either we'd have a URL on our own domain or place a flag on the blockchain.  

Obviously an essential ingredient is authentication of releases (and of course this is true whether they are applied automatically or otherwise).  We need to be resilient even in the event that an attacker successfully compromises pypi or our domain(s).

**Comment by cygnusv** [comment]
wontfix

**Comment by cygnusv** [comment]
Running nucypher as a docker together with a watchtower image is a simple solution for this.
