### ISSUE TITLE
How to calculate work properly?

### ISSUE THREAD

**Issue by vzotova** [nucypher/nucypher#1540]
From #1407, @arjunhassard :
> Possible approaches to this:
> 
> 1. normalise the workToETH function with the participation rate, such that maximal staking (restaking + active + stake > 12m) always means ETH is refunded in 1 year. this approach is complicated by the fact the PR does not stay constant and each staker has a set of unique periods (sub-stakes) over which they received rewards
> 2. more simple: use a constant to enforce a time ceiling – e.g. everyone who works maximally should get their ETH back in ~1 year. So taking a worst case scenario for the average PR, we can choose a value for `boostingRefund` accordingly
>    for example, assuming the highest imaginable PR is 90% , then `boostingRefund` should be ~2
>    *this example assumes a base monthly inflation of 4% and that **all** stakers lock their tokens for >= 12 months and set their stakes to 'auto-prolong'

**Comment by vzotova** [comment]
Also my question is what is work? From previous discussion it seems that work more related to how many effort worker puts and not related how many profit gets. Is it correct that ideal way to calculate work is such parameters: how many tokens staked > 365d relatevily initial amount (from worklock), is re-staked, is auto-prolonged?

**Comment by arjunhassard** [comment]
With regard to the definition of work in the context of worklock, the point @vzotova makes in https://github.com/nucypher/nucypher/pull/1562#issuecomment-574238286 is very relevant here – i.e. rewards don't only vary based on participation rates, but also the epoch of inflation decay in which you start working and the chosen lock-up duration(s). We'd want to avoid edge cases where a staker is unable to reclaim their ETH in a reasonable timeframe because they chose shorter lock-up durations and/or began staking in later epochs, both of which are legitimate actions. This lends weight to the argument for a full and universal expiration of the ETH escrow some number of years after launch.

**Comment by cygnusv** [comment]
Is this issue still relevant given that WorkLock is already deployed with a fixed set of parameters? It looks to me we can simply go with current approach.

**Comment by vzotova** [comment]
This question more about code in `StakingEscrow`

**Comment by cygnusv** [comment]
Sure, but my point is that we already deployed WorkLock under some assumptions, so we don't have anymore a lot of room to change the definition of work.

**Comment by vzotova** [comment]
I see, considering that we guarantee <6m to unlock then yes we don't want to change it
