### ISSUE TITLE
Assorted code reorganizations

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1575]
- [ ] `nucypher.config.node.CharacterConfiguration` --> `nucypher.config.characters.CharacterConfiguration`
- [ ] Reorganize `nucypher.blockchain.eth.sol`
- [x] `nucypher.utilities.sandbox` --> `test.utilities`
...

Let's try to find consensus on each thing.

**Comment by vzotova** [comment]
My opinion:
- "Reorganize `nucypher.blockchain.eth.sol`":
remove directories `eth`, `sol`, `source`, `nucypher.blockchain.eth` -> `nucypher.blockchain`, `nucypher.blockchain.eth.sol` -> `nucypher.blockchain`, `nucypher.blockchain.eth.sol.source` -> `nucypher.blockchain`. I'm strongly for removing `eth` because for me it reads as we have multiple blockchains (or at least have plans for that). But in all docs we talk only about ethereum
- Also I'd like to reorganize contract test directories, remove `eth` directory, extract `contracts.main` directories to one level upper (will be `contracts.base`, `contracts.adjudicator`, `contracts.lib`, etc.), somehow rename `contracts.contracts` (I allways choose wrong directory in IDE :))

**Comment by cygnusv** [comment]
@vzotova Yes, we have to have a common view on the changes. 
E.g. @KPrasch and you are in favour of removing `eth`, while @jMyles is not. I'm sort of neutral, but as usual, I tend to keep status quo.

Wrt to `sol/*` changes, I think we are all on board with that ;)

**Comment by mswilkison** [comment]
This might be a good opportunity to revisit how we envision potentially integrating NuCypher with other blockchains since that might inform what kind of namespace reorgs make sense.

Would there be a situation where we have NU tokens deployed on more than one chain for staking/Sybil-resistance? It's not clear to me how that would even work within the context of one single NuCypher network.

However, it's much more likely/feasible that we'd want nodes to be able to accept policies/payments issued on other smart contract platforms/blockchains.

**Comment by michwill** [comment]
In theory, I can see that very feasible. With a caveat being that Ursulas will get payments in all possible denominations.

I am not sure we know enough to say, how those integrations will look right now. But I think, it's feasible to autoconvert fees to, say, DAI or USDC, and have them going to Ursula's L2 (or L1?) address
