### ISSUE TITLE
Ursula should idle instead of crash if there's no bonded staker

### ISSUE THREAD

**Issue by mswilkison** [nucypher/nucypher#1656]
Currently Ursula crashes on startup if there's no corresponding Staker initiated beforehand. She should idle and wait for a stake instead.

**Comment by BisonAl** [comment]
Thanks for making this issue @mswilkison! Huge help for us, have otherwise been developing a more hacky workaround.

Might also be a good step to idle if the `worker` has yet to be funded. Staked to a new `Ursula` yesterday at
https://goerli.etherscan.io/address/0x4cf0a5c80519b845ae9097ac7b033613d6986fd0, seems no gas was needed on the `Ursula` for the staker to successfully submit the [`setWorker` contract](https://github.com/nucypher/nucypher/blob/6bb3ac49b2c2b40a4493ec244be05a7056e1fbc2/nucypher/blockchain/eth/sol/source/contracts/staking_contracts/StakingInterface.sol#L66-L73).

(Assuming this is correct) This can lead to the scenario where the `Ursula` has been staked to correctly, but will not have the gas to call `approveAndCall` at the start of each round. Believe this will currently also lead to a crash.

**Comment by BisonAl** [comment]
Thanks for making this issue @mswilkison! Huge help for us, have otherwise been developing a workaround.

 There is a second crash scenario we have ran into as well, when the `Ursula` worker does not gas funds for `approveAndCall` at boot up. It should also idle in that scenario.

**Comment by KPrasch** [comment]
It's an interesting moment - Internally we've been discussing preventing Ursula from starting up completely if there is not a staker bonded.  

What workflow do you see as the advantage to allowing a "headless" Ursulas to idle until bonded?
Further scoping: what services do we start during this time, and under what conditions if any do we shutdown an idling node?

**Comment by BisonAl** [comment]
> What workflow do you see as the advantage to allowing a "headless" Ursulas to idle until bonded?

The workflow we follow as a non-custodial service provider is:
1. Customer has locked their `Nucypher` into a staking bond
2. Customer uses our platform to create a new `Ursula` node (configured to work for their staking address)
3. This creation process generates a new wallet/address for the `Ursula` 
4. Customer then bonds their stake to this `Ursula` address 

It's in between steps 2 and 4 that the `Ursula` should idle, as it will be unbonded yet still attempting to run. This will cause a crash, or in our case a crashloop as we automatically attempt to bring the node back online.
