### ISSUE TITLE
Implement a delegation/pooling smart contract

### ISSUE THREAD

**Issue by mswilkison** [nucypher/nucypher#1674]
Many commercial staking operators take a pooling approach that conflicts with NuCypher's 1:1 mapping between stakers and workers. Fortunately, stakers can be smart contracts which means we can implement pooling via a smart contract staker.

It's also important that this contract includes some sort of fee logic, where the staking service can set a fee (likely a % of staking (NU inflation) and/or policy (ETH fees) rewards).

**Comment by vzotova** [comment]
Initial questions:
* deposit: who can deposit (anyone or owner will control the list of stakers) 
* what is stake size: fixed or any size?
* inflation reward: fixed % for owner or depending on owner's stake?
* policy fee: fixed % for owner or depending on owner's stake?
* slashing: how to manage slashing events (for example, everything will be taken from owner's stake)

**Comment by mswilkison** [comment]
> inflation reward: fixed % for owner or depending on owner's stake?
> policy fee: fixed % for owner or depending on owner's stake?

I think the contract owner should be able to set their fee. Pooling services will compete with each other along various dimensions, including their take rate.

**Comment by mswilkison** [comment]
> slashing: how to manage slashing events (for example, everything will be taken from owner's stake)

if we don't have a self-bond requirement, the owner might not have stake to slash.

**Comment by vzotova** [comment]
> > inflation reward: fixed % for owner or depending on owner's stake?
> > policy fee: fixed % for owner or depending on owner's stake?
> 
> I think the contract owner should be able to set their fee. Pooling services will compete with each other along various dimensions, including their take rate.

If owners can set fee - this means it's sort of fixed. But difficult to understand fixed for what metric: by period or fixed % of staking/policy reward or something else

**Comment by mswilkison** [comment]
IMO % of staking reward is most relevant in the short-term (and policy reward over time, so that should be an option as well)

**Comment by ulibkin** [comment]
A delegation contract makes a ton of sense. It is likely that someone will do it anyway (as you all pointed out) so setting the standard is a great way to get ahead of it. 

**A couple of overarching thoughts // comments:**
If folks do not like your policies on these contracts they can and will just fork the contract and change the numbers. This means sensible functionality like delegation with few limitations is probably an overall good strategy. The limitations that do exist should represent protocol limitations as opposed to desired delegation behavior.
It would be nice if whatever functionality is exposed through this contract is also exposed through any user staking interface that the NU team builds.

**Deposit:** 
Deposit is the corollary to delegation? If so, you should use that word, a deposit can mean custody.
Bison Trails believes this should be open, so that anyone with Nucypher tokens can join any pool. Think the alternative of whitelisting stakers per pool would introduce extra complexity and a manual approval overhead, while also sacrificing decentralization. If for regulatory reasons, whitelisting stakers is desired, then giving the option of a whitelisted vs open delegation address would give the flexibility to open staking operations as well as KYCed ones.

**Stake Size:** A minimum and maximum stake both sound ideal. 

Setting a maximum value is a matter of how many nodes your team thinks is optimal for the network, as a lower maximum will encourage more Ursulas. Your team also mentioned there’s a cutoff point where a larger stake won’t translate to work delegated and therefore higher rewards - setting a maximum could be a safeguard for delegates to make sure they don’t stake over this limit. It seems like a maximum is just communicating and reinforcing a protocol level economics decision and this seems like the right way to do it. Make it easier not to make mistakes or have stake offline / not participating in work.

Minimum stakes are a nice way to cap the number of nodes on the network. The reality is, the minimums are not always necessary as the market will dictate the minimum amount of NU you will be willing to stake to infrastructure given the cost of operating, securing and paying for that infrastructure. 

**Inflation reward:** Generally you don’t need to differentiate between node owner tokens and their delegator tokens when accounting for inflation reward. The node runner can take their flat percentage fee of all inflation earned by the node and the remaining inflation can be distributed proportionally to the owners of the tokens staked on that node. That means if there are 100 tokens staked (25 from owner and 75 from delegates) and they earned 20 tokens of rewards, the node owner can set a fee of 10% to get 2 tokens from the top, and then the remaining 18 are distributed proportionately (4.5 to owner and 13.5 to delegates). 

**Inflation fee & policy fee:**
We like Livepeer’s model where the node operators can set a fixed inflation and policy fee for running the nodes. The external delegators can then decide where to delegate based on those fees and the quality of service of those nodes. This makes the amount of money being charged transparent. Having restrictions on how quickly these fees can be changed and by how much is helpful to prevent rate jacking although in practice we don’t see it happen in the market. You should also expect these to change over time as network usage matures and more fees come from policies rather than inflation.

**Slashing:** We think all stake should be slashed equally, so delegators and bonders/operators will face the same proportional penalties. The selection of a node for delegation should really be treated as running the node from a security of the network standpoint. For example - Cosmos validators set a maximum fee rate and the max daily change. So if they charge 20%, have a max of 100%, and can change 1% up or down daily, it’ll take them 80 days to get up to charging 100% of rewards.

**Self Bond Requirement:** No, we generally don’t recommend this requirement. Often a minimum number like 1 NU can make sense here to get things going. But otherwise, bond requirements can cause issues around having node operators and token holders ultimately needing to be the same people. Reputation is much more impactful for staking as service companies and infrastructure providers, so adding a bond increases barrier to entry, increases fees, and worsens UX.

**Comment by vshvsh** [comment]
NuCypher's staking model means that some of the usual approaches are less applicable. Most importantly, NuCypher's staking has nothing to do with network security and consensus, it's essentially nodes doing jobs for money, security and consensus being provided by Ethereum 

That means that a usual ethical responsibility for choosing only trustworthy validators does not apply and an adage of "a delegator should be slashed along with a delegate" is not strictly applicable. 

I think that:

Delegation should be open and not limited by the max/min staking amount. Let the market sort out  what's the minimum viable and maximum economically sound staking amount. 

Node operators can set inflation and policies fees that either can't be easily changed or only apply to new delegations and don't affect older ones.

Self-bond and slashing: I like the model where node operators can have a self-bond that is slashed first, thus protecting the delegators.

**Comment by gaia** [comment]
I think it is interesting to set a minimum staker service fee to keep exchanges from centralizing the chain, and thus rendering it more vulnerable. Not just vulnerable in the traditional sense, but the recent [STEEM's takeover by Justin Sun](https://www.coindesk.com/why-crypto-should-care-about-justin-suns-steem-drama) is just one of the threats made possible by centralized staking.

This minimum fee should be voted upon and revised periodically (NU price goes up, it becomes feasible to properly operate a node with less %).

Other suggestions:

1. Should the delegator chose the period they want to stake for? Possibly the service provider would want to offer lower fees for longer periods.
2. Should the service be allowed to close itself to new delegations (so they can spin down their operation if they wish to do so)?

--------------------------------------------------------------------------------------

Slightly off topic:

I also would suggest that at least the Nucypher maintained staking service ranking list (others can sort as they see fit, and we already know how that goes) uses **decreasing yield as sort metric** (like [Terra's official rank](https://station.terra.money/staking)). Or come up with another default sort, but please do not use total amount staked as default sort - it ONLY serves to make the biggest even bigger.

Another idea to avoid centralization is that any single new delegation that is not a self delegation would be evenly distributed among all service providers, according to an agreed upon coefficient. I can write a lot more about this, including a proposal for said coefficient, but I'm will leave only the TLDR here.

**Comment by pieniedzy** [comment]
> > inflation reward: fixed % for owner or depending on owner's stake?
> > policy fee: fixed % for owner or depending on owner's stake?
> 
> I think the contract owner should be able to set their fee. Pooling services will compete with each other along various dimensions, including their take rate.

It turns out that contract owner will set a competitive fee in order to have an advantage over his competitor, so fee will not be large, because in this case customers will use the services of a competitor, right? Good decision I think:)

**Comment by pieniedzy** [comment]
> * deposit: who can deposit (anyone or owner will control the list of stakers)

Of course owner must control the list of stakers I think

**Comment by pieniedzy** [comment]
> Delegation should be open and not limited by the max/min staking amount. Let the market sort out what's the minimum viable and maximum economically sound staking amount.
> 
> Node operators can set inflation and policies fees that either can't be easily changed or only apply to new delegations and don't affect older ones.
> 
> Self-bond and slashing: I like the model where node operators can have a self-bond that is slashed first, thus protecting the delegators.

Nothing to add, the best choice!👍

**Comment by Niasona** [comment]
I found very interesting post about delegation smart contract.
I don’t know if I can post here a link to this post.

Most interesting:

There a lot of different forms how delegation can be done. Including can the delegated stake be sold? Can we sell the future reward stream from the delegated stake? There is an interesting taxation questions and forms that this can take. Additionally, all of that stake is a capital sitting there that is non operational.
 
Specifically, one create an account / contract that only has a staking key without any fund withdrawal keys. Code deployed to this contract can accept funds into this contract and employ these funds for the staking.

Now, this is just a basic delegation contract now, where validator when creating this contract can decide on rules how to split reward: reinvest? send back to delegators? employ to buy other tokens via Uniswap to hold (for example buy automatically buy DAI as rewards come in).

Multitude of various delegation contracts:

Allow float of tokens in the contracts to improve liquidity of staking. For example keep 10% unstaked in the contract, such that if some people need to undelegate on the short notice, they don’t need to wait for the unbonding period.

Issue a “delegation” token when one deposits into the contract. This delegation token now can be passed / sold between accounts. This allows to make delegated stake liquid.

Control how the proceeds from the staking are split. Fee to the validator, immediate pay out to the delegates or reinvesting back into the staking.

Split control over where reward is going from the owner of the delegated stake.

Use stake that is locked in the contract to issue loans. For example as CDP contract, where stake is used as collateral for issued loan and can automatically maintain various operations to maintain the collateralization as price changes.

Additional possibility is to organize a set of sub-contracts which are controlled by one staking “pool” contract. Each of these sub-contracts can be run by a separate validator and the master contracts can define amounts of the stake allocated to them and define how reward is split.

**Comment by gaia** [comment]
> Allow float of tokens in the contracts to improve liquidity of staking. For example keep 10% unstaked in the contract, such that if some people need to undelegate on the short notice, they don’t need to wait for the unbonding period.

This would also make exchange staking less attractive.
