### ISSUE TITLE
Manual `confirm-activity` command locks account

### ISSUE THREAD

**Issue by vzotova** [nucypher/nucypher#1752]

**Comment by tuxxy** [comment]
To get some clarification on this, you mean if you're running in an interactive session and you try to `confirm-activity`, then it locks the account? Does this happen before or after running the command?

I noticed on my own node that if I didn't use the envvars to set my passwords when I tried to confirm activity interactively, it wouldn't work because the account was locked. However, if I restarted the node and immediately tried to confirm activity, it would work fine. Does this mean that confirm activity is _not_ locking the account, but the account just happens to get locked after a while?

**Comment by vzotova** [comment]
I read multiple issues with this. One of them in interactive mode after successful execution `confirm-activity` - next tx  will fail with locked account. Also one issue was when `confirm-activity` was run in parrallel (with node) successfuly and after this other txs from worker fail with locked account. Restart of node fixs this but until next manual execution of `confirm-activity`.

**Comment by vzotova** [comment]
I guess we can test it like this: start node, wait successful auto `confirm-activity` and then try manual `confirm-activity`. If after this tx - other will work from worker node then we can close this issue

**Comment by KPrasch** [comment]
Closed by #2507
