### ISSUE TITLE
Proposal: Order-based WorkLock distribution

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1760]
1. All bids are sorted. This can be done every time a bid is placed, so the bids are kept sorted all the time. In solidity, this would require just an additional array to store the orders.
2. Let N be the number of bids, T the total worklock supply, m the min stake size, and M the max stake size.
   Let R = T - N*m  (i.e., the remainder tokens, assuming we distribute m tokens to the N bidders)
3. The stake for bidder i is S_i and is computed as:

   `S_i = m + i * 2R / N*(N-1)`

Characteristics of this proposal:
  - It distributes all tokens (modulo small rounding error in the order of NuNits). No need for refunds. No problems with min and max stake.
  - The algorithm succeeds as long as:
     a)  N < T/m, which checks that it's impossible to run out of tokens,e ven if you give the min stake to all the N bidders. This restriction is derived from requiring R > 0. For our current worklock parameters, this means that the number of bidders should be less than 20,000 bidders.
     b)  N > 2T/(M+m), which checks that the stake of the highest bidder can't be larger than the max stake size. This formula is derived from requiring S_{N-1} < M. For our current parameters, the number of bidders should be at least 20.
  - As you can see, the bid amount doesn't matter, but incentizes bidders to bid more than the rest if they want a bigger stake.
  - The exchange rate here will be based on the order of the bids, and will not be proportional to the amount. This is OK, since ETH will be returned anyway if they perform their work.
  - We can put additional restrictions such as not allowing bids equal to an existing bid. We can even restrict a min delta between bids (e.g. 0.1 ETH).
  - We can also put a min bid amount (e.g, 7 ETH), to disallow that very small bids obtain the min stake size.
  - Combining both previous items, we can compute a lower bound on the overall ETH locked as a function on the number of bidders. 
    Let B be the minimum bid and D the min delta between bids, then this lower bound will be:

      Lower bound (N, B, D) = N*B + D*N*(N-1)/2

    For example, for B = 7 eth, D = 0.25 eth, and N = 500, the lower bound is 34687 eth.
 
  - We don't need to put a max bid amount. If you place the largest bid, you will get the largest stake distributed by WorkLock (but not necessarily the max stake size).
  - There's no problem with cancelling at any time, as long as it's before the claiming phase.

Toy example:

  total tokens:	T = 10
  min bid:	m = 2
  num of bids:  N = 3
  
  R = 10 - 2*3 = 4
  
  Stakes:
    S_0 = 2
    S_1 = 2 + 4/3 = 3.33
    S_2 = 2 + 8/3 = 4.66

Somewhat real example:

  total tokens: T = 280 million
  min bid:      m = 15 thousand
  num of bids:  N = 1500 bidders

  R = 280000000 - 15000*1500 = 257500000

  Stakes:
    S_0 = 15,000
    S_300 = 83,712.47
    S_1499 = 358,333.33

**Comment by cygnusv** [comment]
for our worklock parameters (min stake = 14K, max stake=28M), this is the resulting stake of the largest bid, for different values of N (number of bidders). The smallest bid gets 14K always, and the bids in between get something between 14K and whatever the whale got, according to the formula described in the algorithm. 
![unknown](https://user-images.githubusercontent.com/2564234/75973353-4cef0800-5ed5-11ea-806f-4ba363274c4a.png)

**Comment by vzotova** [comment]
Great idea!
I have some concerns:
1. Gas for sorting of bids, but I guess it's will be feasible and not a big issue
2. At the start of bidding a lot of bidders will try to put min bid amount and only one will be accepted and others rejected. Also before bid will be needed to calculate possible bids depending on delta and this is not convinient. 
Maybe add to formula parameter for case when group of bidders has same bid, something like: 
`S_i = m + (i + (Ng-1)/2)* 2R / N*(N-1)`, 
where Ng is group size.

**Comment by derekpierre** [comment]
Very interesting idea!

Some comments:
1. The higher gas cost could just be chalked up to operational costs and doesn't seem to be an issue.

> We can put additional restrictions such as not allowing bids equal to an existing bid. We can even restrict a min delta between bids (e.g. 0.1 ETH).
I guess there will be some extra gas for ensuring that the bid upholds the required delta - since bids are sorted, presumably some sort of search (binary search, or ...) for every bid

2. If we got 20,000 bidders (not sure if that's even a real possibility) does it mean that essentially everyone ends up with the minimum bid regardless of their bid amount? It feels like there may need to be a cut off of the number of bidders to keep the distribution from adjusting whales too much in the downward direction...?

Have we considered not just adjusting max, min stakes/rates - but adjusting the middle of the range - there may be more wiggle room in that range (depending on bids of course) @cygnusv this was similar to our arcsin/logit function discussion in SF... 

3. What happens if there are more than 20,000 bidders (again, this might not even be a real possibility)? Would we have to reduce the min staking amount? OR refunds?...or?

**Comment by electroxts** [comment]
> We can also put a min bid amount (e.g, 7 ETH), to disallow that very small bids obtain the min stake size.

a very good idea as a future participant wanted to see about 5 - 7 ETH minimum threshold

**Comment by ShadovSerg** [comment]
Hi David. It is great idea. 
I will add a couple of my thoughts about this and one possible improvement. They both relate to a fairly uneven distribution of the stake, especially with a small number of participants/bidders N.

1.  It is theoretically possible whales attack. Just before the end of the Worklock, when all bids have already been made, the whale comes and makes t bids with a minimum delta immediately after the maximum bid. And thus will receive a huge share of tokens, up to 50% or more. It spends ~ t*M' ETH on this, where M' is the maximum declared bid. The variable t is directly dependent on the number of bids N (when fixing a certain percentage), t = f(N). 

In real example above N=1500, 
300 max bids will control ~ 1/3 all tokens
500 max bids will control more 50% tokens

For smaller values of N the ratio will be much worse, for example

N=1000
200 max bids will control more 100M tokens
300 max bids will control more 150M tokens

2. Given the fact that a small change in the bid will cause a significant change in the number of tokens, I assume that many people will cancel bids and make them again to get a "better position". Similar to trading bots. This can lead to unpredictable consequences, if you have a fairly stormy imagination you can imagine it :)

To avoid this, I think we need to make a smoother distribution. I think it would be a good idea to introduce a logarithm into the formula and still an absolute value in ethers. I'll think about a specific formula or distribution for a few days...

**Comment by cygnusv** [comment]
@derekpierre

> 1. If we got 20,000 bidders (not sure if that's even a real possibility) does it mean that essentially everyone ends up with the minimum bid regardless of their bid amount? It feels like there may need to be a cut off of the number of bidders to keep the distribution from adjusting whales too much in the downward direction...?
> 3. What happens if there are more than 20,000 bidders (again, this might not even be a real possibility)? Would we have to reduce the min staking amount? OR refunds?...or?

With 20,000 bidders, then it will distribute the same stake to all bidders, being this stake the min stake. And this distribution model, for the initial parameters of token supply, min and max stake size, won't work for more than 20,000 bidders.
I think this is a highly unlikely scenario, but if we're really worried about it, we can just reduce the min stake size: If we set a min stake size of 7K instead of 14K, then this allows up to 40,000 participants, assuming we're still distributing the same number of tokens.

> 2. Have we considered not just adjusting max, min stakes/rates - but adjusting the middle of the range - there may be more wiggle room in that range (depending on bids of course). @cygnusv this was similar to our arcsin/logit function discussion in SF...

 Can you elaborate on this?

**Comment by cygnusv** [comment]
I have an additional idea for the delta between bids.

A naive way to define the delta is to use a fixed amount. Let's use 1 ETH as an example. Then, the only allowed bids are 7, 8, 9, 10, 11, etc. However, this is unfair, since for small bidders, it's much more difficult to achieve a higher bid. For example, the delta between 8 and 7 is an increment of 14%, while the delta between 1001 and 1000 is just 0.1%.

So, let's simply make the delta relative. Let's use a delta of 1% as an example. In this case, the allowed bids would be 7, 7.07, 7.14, 7.21, 7.28, 7.36, etc. 
We can define a formula for the sequence of allowed bid as follows:   `Bids(n) = 7 * (1 + delta)^n`
This way, we're effectively requiring an exponential increment of bid amounts. Going back to the example above, in this model the bids around 1000 ETH are the following: 993.44, 1003.38 and 1013.41. As you can see, while the difference between initial bids is around 0.07 ETH, in this are the difference is roughly 10 ETH. 

So, assuming this model for the deltas, and going back to the examples from @ShadovSerg, I don't see a problem with that whale attack, since for that to happen, the whale would have to lock an enormous amount of ETH due to the exponential distribution of bid amounts.

**Comment by drae12** [comment]
Guys, I used Google to translate this text. Original in Russian https://pastebin.com/3HLL4u0u

I tried to simulate a possible real situation for this auction.
 
Conclusion:
In order to ensure the most fair distribution of tokens by this method, it is necessary to enable each participant to receive approximately the same DepositRate, regardless of his bet amount. This is possible if the delta in ETH between all neighboring bids is approximately equal to the delta between rewards in NU tokens.
 
If this model is implemented, then for the successful Worklock the team will have to do next:
1. ensure the maximum possible number of participants (including whales) with different amounts of ETH;
3. inform about the possibility of placing bids from different stakers;
4. inform each participant as much as possible about the optimal bid strategy within the limits of the budget available to him and the current situation in the auction;
5. Allow each participant to change their bid. preferably at minimal cost.
 

Responding to a message from @ShadovSerg,
1 - a whale attack has less danger / probability than with the current worklock scheme, if the conditions are met:
a) approximately equal DepositRate for all bidders;
b) each participant participates in the auction with the maximum desired amount;
2 - it shall not be prohibited. conversely, trading bots make an auction more efficient. (but I say this from an economic point of view. I do not know how trading bots will affect the ethereum blockchain and / or smart contract)

What I did:
Started by distributing the number of participants into groups, the criterion is the amount of funds available to participate in the worklock.
Made the following assumptions:
- total 1002 participants;
- 75% of participants have 5-50 ETH;
  15% - 50.01-100 ETH
  8% - 100.01 - 500 ETH
  2% - 500.01 - 20 000 ETH.
I made random bids for participants, taking into account the even distribution in groups, sorted in ascending order and calculated the DepositRate (how many NU tokens a participant receives for 1 ETH. The higher this value, the more profitable for the participant).
https://pastebin.com/QM5tifWa
I Adjusted rates for numbers 984-1002. Because Obviously, it is extremely unprofitable for a participant to make such bids. It turned out the following:
https://pastebin.com/mdwtVzyc
 
What can be noted interesting:
- It is obvious that the participant will maximize their DepositRate (after all, everyone wants to get more NU tokens). At the moment, the DepositRate distribution chart looks like this: https://imgur.com/a/HQCjex2 (chart # 1)
Maximum DepositRate is around 750th. Those each participant will try to make a bid about a bit above average in this simulation to receive maximum DepositRate.
- up to a certain point (in my case - at least up to 750th) it is not profitable for me to divide my bid into 2 or more because this reduces DepositRate. After a certain point, the participant is more profitable to do the opposite.
- It makes no sense for a whale to make a big bid (after about 750th) since it turns out very low DepositRate. Perhaps he will not want to work with a bunch of nodes in the future and refuse to split his bid into many smaller ones, or to bid with a low DepositRate. In this case, Worklock will lose the whale. Discrimination of participants with a large number of ETH, after all :)
 
How approximately should the ideal participation in the auction of rational players look (excluding the costs of maintaining multiple nodes);
1. Participants make maximum bids and get schedule # 1 (here it has already been taken into account that the whales will not make excessively high bids).
https://imgur.com/a/HQCjex2
 
2. whales share their bids on many small ones / leave the game / make 1-2 bids with approximately the maximum DepositRate;
 - the smallest players pool or find other opportunities to make a bigger bid.
We get approximately the following situation (we modeled a uniform distribution of bid in the range of 5-250 ETH per 1002 participants):
https://pastebin.com/pagB8SNT
https://imgur.com/a/clAvs2m (graph # 2)
In this case, all participants get an approximately uniform DepositRate value (I think that the high DepositRate value at the beginning will be adjusted in practice).

More interesting observations:
- 1002 participants, even distribution of bids in a narrow range - 5-50 ETH. (the ratio between the delta of the bid and the delta of the received tokens is violated)
Almost every subsequent participant with a higher rate has a higher DepositRate, the bottom top 20-30% has the worst values.
https://pastebin.com/1EEVewM8
https://imgur.com/a/aOGaXec (chart # 3)
- 100 participants, the delta between the bids is relatively large - a range of 5-500 ETH, even distribution of bids.
The lower top 3-4% of participants has a lower DepositRate (the ratio between the delta of the bid and the delta of received tokens is violated significantly only at the top of the list)
https://pastebin.com/FCWiaTYm
https://imgur.com/a/ViW7ZF1 (chart # 4)
 
Now let's try to answer the question: “will a theoretical whale get an advantage over the previous worklock design if it makes a lot of small bids at the last moment?”
 
Take simulation data with graph # 2, where DepositRate is pretty balanced for all participants.
The total amount of bids is 127,205 ETH ($ 31 million). Suppose a whale has 30,000 ETH ($ 7.5 million):
with the current design of the worklock, the whale receives ~ 23.5% of the network. With a new auction - if his DepositRate is in the middle region (~ 2200 with the current simulation), then he gets the same 23.5% of the network (2200 * 30000/280000000) - but for this he needs to make many different bids and have desire / ability to hold 200+ nodes.
If he makes 120 maximum bids at the last moment, he will receive ~ 19.7% of the network. (simplified calculations - https://pastebin.com/ZE6UVvfV), which is not an attack.
 
I do not claim that my calculations are correct.

**Comment by drae12** [comment]
Guys, I translated this text in Google Translate. Original in Russian https://pastebin.com/MTx0Xx1w\

Described below is only my subjective opinion.
 
I think that we should use the old Worklock design and set a small maximum bid in it. 
The main advantage of the new design is the inability of the whale to capture a large % of the network in one bid. However, the same effect can be achieved by setting a small maximum bid in the current design of Worklock. However, in my opinion, there is a real risk of the uneven distribution of DepositRate with an advantage in the direction of the top and / or possible problems from the presence of a bid delta.
 
The main problem of the new auction, in my opinion, is  - the ideal version of this auction (approximately equal DepositRate for all auction participants) is unlikely in real life because:
 - The introduction of a bid delta in the auction, I think, will not work, because there will be a problem mentioned by @vzotova (and if you combine people into groups, this will also negatively affect the even distribution of DepositRate) + many participants will not be able to participate due to lack of necessary funds if small bids are already taken. And if you set the bid delta small, then the top get a higher DepositRate, compared with the bottom top. This will lead to greater centralization of the network in the hands of large players.
 - if you do not implement the bid delta, then the participants are not motivated to place a bet higher than the minimum required value (someone’s bet + 1 wei), which is likely to lead to favorable conditions (high DepositRate) for participants with a large number of ETH;
- It is more profitable for participants to place bets only at the very last moment (@ShadovSerg mentioned this).
 
For the ideal case to happen, you need:
 - A large number of participants with different amounts of ETH;
 - they must place bets with a relatively large and even pitch;
 - be informed of the optimal strategy;
 - often change their rates;
 - actively participate in the auction all the time, and not just at the last moment.

**Comment by derekpierre** [comment]
@cygnusv re: my comment

> Have we considered not just adjusting max, min stakes/rates - but adjusting the middle of the range - there may be more wiggle room in that range (depending on bids of course). @cygnusv this was similar to our arcsin/logit function discussion in SF...

It seemed to me that we were modifying the distribution rates of NU at the min and max ends, and then calculating the rest of the allocations ("middle") relative to those values (eg. min was 7ETH, so 14ETH bid gets 2x), as opposed to possibly modifying the rates across the entire distribution (eg 14ETH doesn't necessarily get you 2x but maybe a modified 1.9x)...am I mistaken there?

**Comment by cygnusv** [comment]
Superseded by #1773
