### ISSUE TITLE
blake2b-py | Use the hashlib included in pyhton 3.6 instead of own package | ARM

### ISSUE THREAD

**Issue by WayneWayner** [nucypher/nucypher#1762]
blake2b-py is already included in python 3.6 hashlib. 
So is there any need to install it as a separate package?

I came up with this because the nucypher setup fails at this point on an ARM CPU.

Maturin is used to install Blake2b-py and is the point where it fails.
https://github.com/PyO3/maturin
The current maturin sources are said to have ARM support since the last pull but I still can't get any further because of new errors.

The best from my point of view would be to leave out the package and use the hashlib.

**Comment by tuxxy** [comment]
Hi, in my opinion (other NuCypherino opinions may vary), launching the network with ARM support is a very bad idea.

At the beginning of launch, it's incredibly important that we have reliable nodes to bootstrap the network. Since NuCypher hasn't been reliably tested on ARM machines (such as Raspberry Pis), I think it's a bad idea to support this from launch.

If ARM support is something we'd like to add, then it should be first integrated into our testing workflow and ideally have a few ARM-based testnet nodes running for a while without issue.

**Comment by WayneWayner** [comment]
I agree that it would be disadvantageous for mainnet to release untested ARMs. But can you prevent this from happening if someone goes for it? 
I thought it would be nice to do the first tests with an ARM on the testnet now.

**Comment by KPrasch** [comment]
Closed by #2837
