### ISSUE TITLE
Batch ERC20 transfer tool

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#1879]
We can either implement it ourselves or use a 3rd party tool.

Here's an idea if we want to implement it:
https://ethereum.stackexchange.com/questions/51513/doing-a-bulk-transaction-with-my-erc20-token-how-to-do-it

**Comment by mswilkison** [comment]
@cygnusv comment in Discord:
"""
@maclane @michwill re: sending the SAFT 1 tokens, here's a Dapp that does this using a smart contract. In our case, it seems it can transfer all tokens in a single TX (instead of ~45 individual TXs)
https://github.com/rstormsf/multisender
GitHub
rstormsf/multisender
Token Multisender Dapp smart contract. Airdrop tokens. Batch sending ERC20, ETH, Ethereum tokens. Send thousands of transfers in a few transactions - rstormsf/multisender

They were talking about batch ERC20 transfers in the ETHSecurity TG group and this tool was mentioned. Apparently MyCrypto is working on that too on their beta site, but I couldn't find it.
"""

**Comment by rstormsf** [comment]
Feel free to reach out if you need some help with https://multisender.app
