### ISSUE TITLE
Documentation for backing up policies and re-encryption keys

### ISSUE THREAD

**Issue by mswilkison** [nucypher/nucypher#1908]

**Comment by derekpierre** [comment]
@mswilkison / @KPrasch do we already have this functionality implemented?

**Comment by mswilkison** [comment]
AFAIK, we do not. You have to do it manually: https://github.com/c29r3/nucypher-backup-script

**Comment by derekpierre** [comment]
So based on those scripts, to backup the Worker (Ursula), we just need to instruct the user to store copies of the following folders:
1. Worker (Ursula) data: `~/.local/share/nucypher/`
2. Local ethereum keystore: `~/.ethereum/keystore`

Is that complete?

**Comment by KPrasch** [comment]
For completeness, I think we need to actually introduce a migration command for ursula CLI.

**Comment by derekpierre** [comment]
Filed #1992. I set the milestone as `Mainnet Month 1` instead of `Before activating StakersEscrow` since there is an existing workaround in the meantime. Any objections pushing this documentation issue to `Mainnet Month 1` as well? If pivotal I could provide simple manual instructions with a note about future dev effort to add a command to the Ursula CLI.

**Comment by KPrasch** [comment]
I think that's a clear re-prioritization.  I say move it!

**Comment by cygnusv** [comment]
Fixed by TreasureMaps con KFrags #2687 , as nodes don't store anymore re-encryption keys.
