### ISSUE TITLE
Use common exit method and strategy for CLI command termination.

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1984]
Control the exit codes!

**Comment by cygnusv** [comment]
Related to this: there are some cases where it's unclear to me if the situation deserves an error or not. 
For example, see e1f59aab20f7dc4dee819d81e3abbcbe20e22051. In this case, the command aborts when a WorkLock bidder tries to claim twice. The previous behavior was to `return` so the exit code was 0, and I changed it to a `click.Abort()`. When fixing the test I started to have second thoughts since we don't have a unified criteria for this.

**Comment by fjarri** [comment]
Can someone expand on the issue a little? What's the problem that needs to be solved here?

**Comment by fjarri** [comment]
This is related to #1642

We could use standard *nix user exit codes (from `sysexit.h`), but `click` already violates those conventions by using the exit code 2 (permission denied) for bad option usage. So perhaps the following general strategy should be applied:  

* If the error can be described by one of [`click`'s exceptions](https://click.palletsprojects.com/en/7.x/api/#exceptions), this exception should be used
* If nothing fits, use `click.Abort()`
* If there is an exception raised deep in the codebase, it should be caught, call stack written to the log (which will mirror it to the console if the verbosity level is high enough), and a suitable `click` exception with a clear explanation for the user raised instead.

Regarding the last point, since it is hard to tell what *can* throw an unhandled exception in all the codebase, perhaps make this issue (or #1642) the Wailing Wall for all the cases when you saw an unexplained exception in the console output?

**Comment by fjarri** [comment]
As for e1f59aa, I think an error there is justified, but the `CLAIM_ALREADY_PLACED` constant should have the cross symbol in the beginning - now it reads like a warning.

**Comment by KPrasch** [comment]
> perhaps make this issue (or #1642) the Wailing Wall for all the cases when you saw an unexplained exception in the console output?

Yes - this is totally reasonable.  With that in mind I suggest we move this Issue to another milestone.

**Comment by KPrasch** [comment]
This discussion leads me to think that we can move this Issue to the next milestone.

**Comment by KPrasch** [comment]
Related to #1515
