### ISSUE TITLE
Decide initial DAO parameters (% support, % approval, duration)

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2089]
We need to decide the initial parameters (% support, % approval, duration), for both validation tracks

**Comment by cygnusv** [comment]
For standard proposal validation, I propose here some ranges for the main parameters:

- Duration: Something between 3-5 days
   - 1 or 2 days it's probably not enough time for discussion and informing yourself, specially with stakers from all over the world. On the other hand, 5 days seems to me like more than enough. 
- Minimum Percentage of Support: Between 50% and 66%
  - Support is the ratio between Yes and No. Obviously it has to be >50%, but more than 66% (2/3) is probably excessive.
- Minimum Percentage of Approval: Something around 20-30%?
  - Approval is the ratio between Yes and the global balance of tokens (i.e., it's related to participation). This one is really hard to justify objectively. With a high approval requirement, we risk that the DAO can't have enough participation to validate some proposals, but with a very low approval requirement, we risk getting results that are not representative enough (again, in case of low participation).

**Comment by cygnusv** [comment]
Apart from the "standard" proposal validation track, we need to decide the parameters for the "emergency" track (i.e., the one used by the Emergency Response Team, previously called "Security Council"). Recall that this team is comprised of 3 people. 

My proposal:
* Duration: Something less than 1 hour
* Min support: 65%  (or anything strictly between 1/3 and 2/3)
* Min approval: 65%. (or anything strictly between 1/3 and 2/3)

The rationale for anything strictly between 1/3 and 2/3 is that it allows to pass proposals with 2 out of 3 members, in the event of the third member not participating, or participating with rejection.

**Comment by gaia** [comment]
I'd give it 7 days at least, if not 10 days.

Sometimes after a proposal goes to voting and only then you get people to pay attn to it.
And sometimes questions will come up regarding the proposal that need clarification, some of which had not been thought out before. And it takes time to come up with and/or communicate the proper answers to these potential questions.

Sure, in an ideal world ppl would pay attention during the proposal phase not the voting phase. But governance can be frustrating sometimes.

**Comment by nickhill** [comment]
I think 5 days might be too short, especially if it cannot be changed without relaunching the DAO.
Historically, gathering participants for DAO governance has proven quite difficult.
Those who ARE inclined to participate come and go, building a quorum can be ... tough.
Getting the word out to those who aren't paying attention (for whatever reasons) is the constant problem.

Should a person inclined to participate go on vacation for more than a few days, or has an emergency or whatever... 5 days is way too short.
There may be huge, involved discussions arising around some proposal, hasty decisions can be less good than sometimes overly-long waiting periods.
There is neither a "right" nor perfect answer.
The original, Slock.it DAO provided a 14 day debate period for proposals.
Though I haven't really looked around in DAO-worlds in a while, I haven't heard of a compelling reason not to make it 2 weeks.
Note that

- not many are actually going to participate, and not more than a few times, based on what I've seen go on

- folks who ARE inclined to participate often need more than 5 days due to life's interventions, or their involvement in other projects etc.

- when some issue spawns a contentious discussion, 2 weeks is sometimes insufficient.

- the choices are not easily changed via proposal with Aragon, according to what I see above

That this is a question... I find mildly worrisome. I haven't examined your DAO structure yet,
but %support, %approval and duration are pretty critical and I urge you all to think deeply about your choices,
review what others are doing along those lines.

**Comment by cygnusv** [comment]
Thanks @gaia @nickhill ! These are great input for us.

As a matter of fact, 5 days seems to be in the ballpark of other DAOs I've seen in the wild:
- Yearn: 3 days
- Compound: 3 days
- Curve: 7 days
- Maker: 14 days

Having said that, I don't think 7 or 10 days is unreasonable (again, it's in the same range as other DAOs), and you give very compelling arguments. That's why we opened this public discussion.

Regarding other parameters, the second trickiest parameter is Support. I originally suggested something like 20 or 30%. [Yearn recently changed it from 33.3% to 20%](https://yips.yearn.finance/YIPS/yip-12), precisely because it's very difficult to foresee what's going to be the actual participation of the community. However, this parameter can be changed with a proposal, so it's not that problematic. We can learn along the way. If you ask me, I'd say something closer to 20%, rather than to 30%, but also that's why we wanted to bring this discussion to the staking community.

**Comment by gaia** [comment]
Yearn, Compound, Curve & Maker have highly motivated stakeholders, and the purpose of each DAO decision is to increase the safety or profitability of their investment. They also have a token specifically created for voting - if you hold it you are more likely to be voting. Lastly, the people using those platforms are extremely dedicated to the crypto space.

NU is a token that has it's native intended use, a speculative use AND a potential voting use, with the mix of people that come with these diverse use scenarios. I personally think it is overly optimistic to use those 4 as examples.

Also note that those 4 have sometimes have to vote on urgent governance related issues. Change a fee, change issuance, open/close a vault. I don't see Nucypher having those urgent issues - the urgent issues in Nucypher are likely related to bugs and will be fixed by code, not governance.

**Comment by cygnusv** [comment]
> the urgent issues in Nucypher are likely related to bugs and will be fixed by code, not governance.

This last point is not completely true, as when the DAO owns NuCypher contracts, then the DAO is the ultimate authority in enacting a fix. Sure, the code must be created by someone from the community (that being a staker, the NuCypher team, etc.), but approving and upgrading the contracts depends on the DAO.

**Comment by cygnusv** [comment]
Thanks everyone for your insights! The initial DAO configuration is done with the following parameters:

**Standard validation track**

- Duration: 14 days (see final discussion [here](https://dao.nucypher.com/t/duration-of-proposals-validation-process/27))
- Support: 60%
- Approval: 25%

**Emergency track**

- Duration: 12 hours
- Support: 65%
- Approval: 65%
