### ISSUE TITLE
Viral spread for incidental payloads

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2124]
Presently, only qualifying nodes (per `matching_nodes_among(some_nodes, ...)`) *at grant time* receive a Treasure Map.  It makes sense to also enlist nodes to spread incidental payloads to other qualifying nodes later in their runtime.

**Comment by jMyles** [comment]
This issue is totally unimportant until suddenly it's very important.  I'm inclined to put this in the "Before Activating" milestone.

**Comment by cygnusv** [comment]
As a follow-up of my comment here (https://github.com/nucypher/nucypher/pull/1741#discussion_r482238973), I have this idea for an alternative method for `Bob.matching_nodes`:

```python
def matching_nodes(self, nodes: FleetSensor):

    bob_bytes = bytes(self.public_keys(DecryptingPower))

    def node_index(canonical_address: bytes) -> int:
        digest = SHA256(bob_bytes + canonical_address)  # potentially some metadata too (e.g. label?)
        index = int.from_bytes(digest, 'big')
        return index

    indexed_nodes = sorted([(node_index(node.canonical_public_address), node) for node in nodes])
    target_nodes = list(zip(*indexed_nodes))[1]
    return target_nodes
```
Instead of giving you a selection of nodes, this would give you a _deterministic ordering_ of nodes, where you're guaranteed that the TMap is in some of the first nodes of that list (assuming there's still one of these original Ursulas online, obviously). This would work even as the network grows, at the expense of decreasing the success probability for Bob per Ursula (i.e, if the network is 10 times bigger, then Bob will get a 10x longer list, with ~9 false positives in that list per correct Ursula).

**Comment by jMyles** [comment]
1) I don't like the idea of adding policy-dependent metadata (such as the label), for reasons I describe here: https://hackmd.io/GEpM-Sr8SR6QzVtXYOQj3g

2) I don't like the idea of Bob needing to perform an additional SHA256 for every node on the network at retrieve time.

3) This method gives a list of *all the nodes*.  To how many nodes does Alice deliver in this scenario?

**Comment by cygnusv** [comment]
Random failure related to current search-boundary approach:
https://app.circleci.com/pipelines/github/nucypher/nucypher/6086/workflows/0eb2e11a-0504-4610-83a0-dc6b09188156/jobs/105465

**Comment by KPrasch** [comment]
I do not think this issue is oily rags.

**Comment by cygnusv** [comment]
There's no incidental payloads anymore, as TMaps distribution is handled outside of the protocol
