### ISSUE TITLE
Use lower lmdb memory allocation in tests to avoid failure

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2172]

**Comment by tuxxy** [comment]
Thanks for opening this issue.

What evidence is there that the current solution isn't enough? Is the problem still apparent after machine restart or equivalent?

**Comment by KPrasch** [comment]
> Thanks for opening this issue.

:+1: 

> What evidence is there that the current solution isn't enough? 

When running groups of tests that include multiple concurrent running ursulas (like the integration suite) an exception is raised:

```
    @pytest.fixture(scope="module")
    def federated_ursulas(ursula_federated_test_config):
>       _ursulas = make_federated_ursulas(ursula_config=ursula_federated_test_config,
                                          quantity=NUMBER_OF_URSULAS_IN_DEVELOPMENT_NETWORK)

../fixtures.py:367: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../utils/ursula.py:69: in make_federated_ursulas
    ursula = ursula_config.produce(rest_port=port + 100,
../../nucypher/config/characters.py:109: in produce
    ursula = self.CHARACTER_CLASS(**merged_parameters)
../../nucypher/characters/lawful.py:1022: in __init__
    rest_app, datastore = make_rest_app(
../../nucypher/network/server.py:92: in make_rest_app
    datastore = datastore.Datastore(db_filepath)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <nucypher.datastore.datastore.Datastore object at 0x2c69d5fbe7c0>
db_path = '/tmp/tmpklq6py8i'

    def __init__(self, db_path: str) -> None:
        """
        Initializes a Datastore object by path.
    
        :param db_path: Filepath to a lmdb database.
        """
        self.db_path = db_path
>       self.__db_env = lmdb.open(db_path, map_size=self.LMDB_MAP_SIZE)
E       lmdb.MemoryError: /tmp/tmpklq6py8i: Cannot allocate memory

../../nucypher/datastore/datastore.py:96: MemoryError

```

> Is the problem still apparent after machine restart or equivalent?

Yes - on my development laptop a full hardware restart with minimal applications running still causes thus issue to raise an exception.

**Comment by tuxxy** [comment]
Ah, so this is probably happening due to the fixture that sets the smaller memory footprint not being collected in unit tests.

**Comment by KPrasch** [comment]
Related to #1741

**Comment by tuxxy** [comment]
If no one else is getting this error anymore, then it seems to be done.

**Comment by KPrasch** [comment]
Still happens for me in local tests regularly based on 9cabd4ebefaa38ed017b28da35dd617ff6fb9236

**Comment by fjarri** [comment]
Ok, so this is a bit more involved than I thought.

First issue is the reduced DB sized not being set. `Datastore` is created in two fixtures: `lonely_ursula_maker` (function-scope) and `federated_ursulas` (module-scope). `reduced_memory_page_lmdb` is function-scope, so it gets applied *after* `federated_ursulas` creates Ursulas, and therefore has no effect on any tests that use it.

`reduced_memory_page_lmdb` cannot be made module-scope since `monkeypatch` is function-scope, and there is no documented way to use it otherwise (see https://github.com/pytest-dev/pytest/issues/363).

One can do the patching with `unittest.mock.patch.object()`, but it either has to be made into a context manager and used explicitly, or two fixtures (function-scope and module-scope) need to be created, since there's no any-scope in Pytest at the moment. I would personally prefer the former - I dislike `autouse`, and `reduced_memory_page_lmdb` is only used in two other fixtures anyway.

When that is fixed though, and one can see from debug printouts that `Database` is always created with a reduced file size, the error still persists. To be continued.

**Comment by fjarri** [comment]
Ok, the second problem is, naturally, too many open files. Each `Datastore` opens some file handles, never gets deleted, and the number of open files overflows the limit - which is not too large, 256 on my system, and probably the same on many others by default. 

When `Ursula` is created, it creates the datastore and the REST app, with references looking like (`->` means "holds a reference to"):

* `Ursula` -> `rest_server`
* `rest_server` -> `rest_app`
* `rest_server` -> `datastore`
* `rest_app` -> closure from `make_rest_app()`
* closure from `make_rest_app()` -> `datastore`, `Ursula` (passed as `this_node` to `make_rest_app()`)
 
So there is a reference cycle happening. In addition to that, `Ursula` objects created in `federated_ursulas()` (and perhaps in other places, haven't checked yet) don't get deleted either - `pytest` is known to hold on to references to whatever is yielded by fixtures (and it's not going to get fixed - see https://github.com/pytest-dev/pytest/issues/5642).

Fixing that seems to get rid of the issue. Going to make a PR now.
