### ISSUE TITLE
Consider specifying `--release-period` in the deploy CLI as a datetime string

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#2194]
@vzotova / @cygnusv you can judge best whether this is worth it or not - just a thought.

Related to #2191 (see https://github.com/nucypher/nucypher/pull/2191#discussion_r476538044).

The actual "release period" for the restake lock can then be programmatically calculated from the datetime, and we don't need to calculate it before using the CLI.

**Comment by cygnusv** [comment]
I'm not sure if it's going to remove complexity. For those of you living in the New Continent, new periods start during your day (e.g, 17:00 in California), which implies that you'd need to think not only date but also time of the day in order to ascertain what period are you actually referring to. Using periods from the start seems like a better standard to me.

**Comment by derekpierre** [comment]
How would you currently calculate the release period to input into the CLI?
