### ISSUE TITLE
Complete enviorment variables documentation table

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2255]

**Comment by mloop1** [comment]
Currently there is the following text in "Running an Ursula with Docker"

**Running an Ursula with Docker
Assuming geth is running locally, configure and run an Ursula using port and volume bindings:

export NUCYPHER_KEYRING_PASSWORD=<YOUR KEYRING_PASSWORD>
export NUCYPHER_WORKER_ETH_PASSWORD=<YOUR WORKER ETH ACCOUNT PASSWORD>**

It would be nice to clarify that the NUCYPHER_KEYRING_PASSWORD needs to be created at this point, otherwise it seems that should be a password already in possesion of the user like it is for NUCYPHER_WORKER_ETH_PASSWORD.

**Comment by cygnusv** [comment]
https://docs.nucypher.com/en/latest/guides/environment_variables.html
