### ISSUE TITLE
Why is use of existing registry contingent on specifying a contract name in nucypher-deploy cli

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#2314]
Related to work for #2313
```
        #
        # Establish Registry
        #
        local_registry = establish_deployer_registry(emitter=emitter,
                                                     use_existing_registry=bool(self.contract_name),   <----- Huh?
                                                     registry_infile=self.registry_infile,
                                                     registry_outfile=self.registry_outfile,
                                                     dev=self.dev)
```

Resolving this will allow contract name to be required for all deploy commands except for `set_range`.

**Comment by cygnusv** [comment]
The way I understand this is that sometimes you want to deploy a complete set of smart contracts, not individually, which is actually the default method for `nucypher-deploy contracts` (without `--contract-name`). In this case, it makes sense to start with a brand new registry. Otherwise, it's the opposite: if you're deploying contracts individually, then it can be assumed that a network/registry already exists and that you want to use an existing registry.

Having said that, I agree that this logic can be improved. In fact, I would improve it by removing the deploy mode where all contracts are deployed in a row. It's an overly optimistic mode. It's basically used just in tests; in a real setting there has been reasons to do deployments manually – in general, improved control of the deployment, greater assurance, possibility of human intervention and double or triple checking, etc.

**Comment by cygnusv** [comment]
Seems to be addressed by #2315

**Comment by KPrasch** [comment]
Not completely - I'd like to remove this flag from actor group options, thus allowing `--contract-name` to be controlled with a per-command basis, with some required and some optional.

**Comment by KPrasch** [comment]
#2319 makes `--network` required for all `nucypher-deploy` commands, even though not all methods use it, it's the most backward-compatible change and allows for a bit of additional context to be used for checks.
