### ISSUE TITLE
Restart on unhandled errors in the work tracking loop

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#2411]
Presently, our work tracking loop errback handler, `handle_working_errors`, has no way to call `start` on its `LoopingCall` (`self._tracking_task.start`).

Let's to do this automatically `if not self._abort_on_error`.  This (along with actually changing `self._abort_on_error` to `False`) will prevent one path by which nodes fall into the odd limbo state where a loop has crashed but the node marches on.

**Comment by cygnusv** [comment]
Unfortunately, there seems to be a regression since this is happening again. In particular, this occurred cause by Infura's outage on Nov 11th 2020, which caused request errors temporarily:
```
503 Server Error: Service Unavailable for url: https://mainnet.infura.io/v3/...
builtins.ValueError: {'code': -32603, 'message': 'request failed or timed out'}
```
Several nodes using Infura were affected by this, and while their worker kept running, the stake-tracker was dead.

**Comment by KPrasch** [comment]
this issue can no longer be reproduced
