### ISSUE TITLE
Limit sampling resivoir by node labels

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#2478]
Related to #2311 

Compare the HTTP request's origin IP address when verifying ursula interfaces. Currently node validity only considers the serialized representation of ursula matches the signatures recovered address. This leaves "ghost ursulas" on the network: metadata belonging to a node whose IP address changed and host was relocated.

This reduces the availability of grant since sampled nodes must be available to receive key fragments, and have an up-to-date IP addresses to receive grant requests.

**Comment by KPrasch** [comment]
Related to PR #2462

**Comment by cygnusv** [comment]
See how we're currently assessing REST interface validity 🙈 :
```python
    def validate_interface(self) -> bool:
        """
        Checks that the interface info is valid for this node's canonical address.
        """
        interface_info_message = self._signable_interface_info_message()  # Contains canonical address.
        message = self.timestamp_bytes() + interface_info_message
        interface_is_valid = self._interface_signature.verify(message, self.public_keys(SigningPower))
        self.verified_interface = interface_is_valid
        if interface_is_valid:
            return True
        else:
            raise self.InvalidNode("Interface is not valid")

    def _signable_interface_info_message(self):
        message = self.canonical_public_address + self.rest_interface
        return message
```

**Comment by jMyles** [comment]
The apparent goal of this issue, as described [here](https://discord.com/channels/411401661714792449/411401661714792451/798223354048806963), is to solve the problem of (for example) `Alice` having to 'sift' through ghost nodes, whose once-valid metadata appears in the canonical fleet state, but which are no longer operating at the given IP address.

This causes timeouts, etc.

However, I'm not sure I understand the actual motions at work here.  For example, what does "Compare the HTTP request's origin IP address when verifying ursula interfaces" *actually* mean?

"When verifying" a given `Ursula`, a `Learner` will *use the IP address in the metadata to connect to it*, right?  Thus, if the connection occurs, the IP address is correct. 

In other words, fixing this here doesn't seem possible (and if it were - ie, eagerly verify all nodes as soon as their metadata is discovered).

Instead, it seems to me that the real problem is that a `Teacher` only has one bucket of nodes, rather than a separate bucket for those whose IP address is known-good at last verification time.  

The clearest example of this is `nucypher.network.nodes.Teacher.bytestring_of_known_nodes` - here we cast *all* known nodes (including some that are just outright bupkis) and pass them along, hoping `Alice` will sort it out.  WHY?  Well, because we have always built this tooling assuming that #567 was going to be fixed before mainnet.  

When it is, we can have only one bucket of nodes which are manifestly safe to propagate: those that have already been verified, and whose metadata has not subsequently been supplanted by properly obseleting (and verified) metadata (see #2408).
