### ISSUE TITLE
Find a suitable way to set and update the max gas price limit

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#2485]
PR #2445 introduces a max gas price limit configurable via the `NUCYPHER_MAX_GAS_PRICE_GWEI` envvar.
There's some disagreement wrt to the use of the envvar for this. Let's explore what other alternatives we have that allow node operators to change the limit at runtime.

**Comment by vepkenez** [comment]
In that case should we move all gas affecting configuration to envvars?
Why is --gas-strategy a cli arg?
Should it also be modifiable at runtime?

**Comment by cygnusv** [comment]
That's a good point, I didn't think about this from that perspective. Well played, ser.
In that case, I agree a configuration is a better fit. What would be awesome is some mechanism that detects at runtime a configuration change and updates whatever needs to be updated dynamically. That's definitely outside the scope of #2445, but I guess that making the change from envvar to configuration value is OK. What do you think @vepkenez @KPrasch ?

**Comment by vepkenez** [comment]
In my opinion, it is most important that they are consistent.
As an operator of nodes, it would be easier if all these gas params were environment variables for the reasons you mention, as well as that it's just simpler that way.

If we were to devise some coherent philosophy on what works better as a "configuration" vs an ENVVAR, I think that static values that are essential to a character's identity and core functioning make sense as configuration, and values likely to change at any time which don't effect the actual essence of a node make more sense as ENVVARs.

So I would vote that we make everything that people might want to change with the weather into ENVVARs, rather than move them into configurations...  I don't feel strongly about any of this.

**Comment by KPrasch** [comment]
Definitely an area of great thinking before us - Ill just leave this here: https://stackoverflow.com/questions/7443366/argument-passing-strategy-environment-variables-vs-command-line

**Comment by cygnusv** [comment]
Based on the discussion here, #2445 changed its approach and used a configuration value, so this issue can be closed.
