### ISSUE TITLE
A Publisher character should take on most of Alice's responsibilities

### ISSUE THREAD

**Issue by fjarri** [nucypher/nucypher#2752]
Following the introduction of a "publisher" who handles treasure map creation in #2687, and some additional renames in #2745, it became clear that essentially most of what `Alice` currently does is the job of a `Publisher` (Pablo?). In particular, everywhere "Alice" is mentioned in `policies.py`, it should be a `Publisher`. Essentially, one can just rename the existing Alice to Publisher *everywhere*, and then introduce a new `Alice` character which will be responsible for generating kfrags - it should be a rather lightweight object (e.g. it doesn't need to be a `Learner`), resembling an `Enrico`.

**Comment by derekpierre** [comment]
I have some reservations about creating a "Pablo character" for this but I'm interested in better understanding the scope.

1. Was the original basis for this issue the fact that we were changing lots of `alice_verifying_key` -> `publisher_verifying_key` and it felt that the publisher was taking over Alice's use? Since Alice can also be a publisher could this be:
      a) A naming thing for the parameter i.e. instead of `publisher_verifying_key` just call it `verifying_key`?
      b) If an object is needed, is it possible the "Publisher" is more like a utility class such as something like `TreasureMapPublisher, or something that can be passed around, and may not need to be a character/learner at all. Presumably, the goal of the "Publisher" is to take some verifying_key (Alice's or external) and perhaps other associated objects, and use/provide them to publish a treasure map.

2. When you say *"(e.g. it doesn't need to be a Learner), resembling an Enrico"*; a Character is a sub-class of Learner - which raises the question of why Enrico was a Character in the first place since it feels like neither a character nor a Learner. IMO We may have retrofitted Enrico into a character, although perhaps there was some other reason that I'm unaware of. Of course, the Enrico boat has sailed, but I want to be careful of doing that again.

**Comment by fjarri** [comment]
The renaming was prompted by the fact that "Kfrag producer" and "Tmap producer" could be two different characters, and we wanted to emphasize it in variable names. They can both be of type `Alice`, but the names should still reflect that they're different objects. I thought that was pretty much settled in #2687, and in #2745 I was just finishing up the renaming.

Now that we made that separation, we might want to make them different types as well, since "Kfrag producer" doesn't really need to be a Learner.

> A naming thing for the parameter i.e. instead of `publisher_verifying_key` just call it `verifying_key`?

Are you talking about some specific function, or everywhere? I feel like that may be confusing - whose key should it be? Perhaps at high level we should make an effort to pass around keys wrapped in characters and not by themselves?

> If an object is needed, is it possible the "Publisher" is more like a utility class such as something like `TreasureMapPublisher`, or something that can be passed around, and may not need to be a character/learner at all.

We pass around even Ursula objects. What we're missing here is the separation of character's public info vs a full character (with private keys and whatnot). 

> Presumably, the goal of the "Publisher" is to take some verifying_key (Alice's or external) and perhaps other associated objects, and use/provide them to publish a treasure map.

The publisher needs to own the stamp too to do the publishing, not just the public key.

> When you say "(e.g. it doesn't need to be a Learner), resembling an Enrico"; a Character is a sub-class of Learner - which raises the question of why Enrico was a Character in the first place since it feels like neither a character nor a Learner.

I don't actually know why `Character` is derived from `Learner`. The way I see it, `Character` can be a pretty minimal base class, and what we now call a `Character` is more of a `NetworkCharacter`. A character is just a wrapper on top of some keys and identifying info.

**Comment by derekpierre** [comment]
> Are you talking about some specific function, or everywhere? I feel like that may be confusing - whose key should it be? Perhaps at high level we should make an effort to pass around keys wrapped in characters and not by themselves?

Ah. The initial changes I saw revolved around renaming of a parameter, but it seems the changes go even deeper than that. I guess my initial thought missed the fact that some actual signing still needed to occur, and not just passing around a public verifying key. 

Interesting, since Alice can also be the publisher of the policy, if we want a more lean version of Alice, the "Publisher" character should be able to be created from an Alice, or maybe more like take an Alice to maintain separation of sensitive material ...

> A character is just a wrapper on top of some keys and identifying info.

Agree with you here.
