### ISSUE TITLE
Implement a Porter proxy for messages intended for Ursulas

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/nucypher#2763]
Browser-based integrations are impaired by self-signed certificates used by Ursulas.

We could solve that by implementing a proxy in Porter API. The proxy client could send a request with a header specifying destination: `X-API-DESTINATION: https://ursulas.address.com`. Then, Porter would re-send that request and respond to the client synchronously:

```
              Browser                          Porter           Ursula
                                                         (https://ursula.com)
     POST /proxy/consider_arrangement           ┌─┐
X-PROXY-DESTINATION: https://ursula.com  ───────► │
                                                │ ├─────────────┐
                                                │ │             │
                                                │ │◄────────────┘
                 Ok◄────────────────────────────┤ │
                                                └─┘               
``` 

Porter should proxy following endpoints: 
* propose arrangements `POST /proxy/consider_arrangement` 
* send kFrags `POST /proxy/kFrag/<kFragId>` (transient until TMapConKFrags ships)

This simplified implementation would suffice to enable in-browser use by `nucypher-ts`.

**Comment by derekpierre** [comment]
Some initial thoughts:
1. I believe that the `/kfrag` endpoint would go away with TMapConKFrags - is this needed until that is completed? i.e. only transient
2. Has there been any conversation about potentially subsuming the proposed proxy endpoints under a single path? for example
   * proxy/consider_arrangement
   * proxy/kFrag/<kfragId>
   
   Of course, the name does not need to be "proxy" and could be something else. This would help to differentiate proxied functionality from the original base Porter functionality which does not require the `X-PROXY-DESTINATION` header.

**Comment by derekpierre** [comment]
@piotr-roslaniec, with TMapConKfrags merged, is this issue still required?

**Comment by piotr-roslaniec** [comment]
@derekpierre We still need to handle `/consider_arrangement` for purpose of enacting policies in the `nucypher-ts`.

**Comment by derekpierre** [comment]
Ok. Interested to see what you expect/need as input and output (@KPrasch , @piotr-roslaniec , @vepkenez )

Presumably, since an Arrangement is only an expiration date and a publisher verifying key, we can have those specified and then a list of ursulas to send it to? Or do we need Alice to create Arrangement objects for each Ursula to then send to Porter? If not, Porter can create the arrangement internally and then have them be signed by respective Ursulas.

Something like:

`/proxy/consider_arrangements`
---------------------------------

**Request**
```
{
	"publisher_verifying_key": <>,
	"expiration": <>,
	"ursulas": [...]
}
```

The question then becomes, is Porter trusted to verify the signed arrangement after Ursula have accepted them? Porter can verify the arrangement, and also return it. Something like:

**Response**
```
"result": {
    "arrangement": <bytes of arrangement object (base64 encoded)>,
    "accepted": [
            "<ursula_1_checksum>": {
                  "signature": <>,
                  "ursula_verfiying_key": <>
            }
            "<ursula_2_checksum>": {
                  "signature": <>,
                  "ursula_verfiying_key": <>
            }
     ]
     "rejected": {
            <ursula_3_checksum>: <status code>,
            <ursula_4_checksum>: <status code>
     }
}
```

We can include the arrangement bytes so that callers can do their own verification of signatures if needed.

So outstanding questions/comments:
1. Does there need to be a 1:1 relationship between Arrangement and Ursula? I assumed not in the above
2. Is there an expectation that Porter would verify the the Ursula accepting an arrangement, or that the caller should be able to do the verification themself irrespective of whether Porter does it or not - the above assumes both. 
3. My goal is keep the request flat to continue to allow for URL query parameters.
4. This was based on a quick view of the code, and I may have missed some nuance. Perhaps you have already given thought to endpoint - interested to get your take of what the expected inputs/outputs would be.

**Comment by piotr-roslaniec** [comment]
> Is it simply just passing the original consider_arrangement request? 
Yes, that was the original reason. On second thought, `consider_arrangement` is there just to make sure Ursulas have sufficient staking periods, correct? If that's still necessary, maybe we could shift that logic to `/get_ursulas`?

> Does there need to be a 1:1 relationship between Arrangement and Ursula? I assumed not in the above
I can't think of a reason to introduce this relationship. `/get_ursulas` allows Alice to include and exclude certain Ursulas - I think this degree of control should be satisfying to the end-user.

> Is there an expectation that Porter would verify the Ursula accepting an arrangement, or that the caller should be able to do the verification themself irrespective of whether Porter does it or not - the above assumes both.
I'm not sure if potential benefits (flexibility, shifting work/responsibility to Porter) are outweighing potential downsides (complexity, risk of misconfiguration, Porter DoS vector).

**Comment by derekpierre** [comment]
> On second thought, consider_arrangement is there just to make sure Ursulas have sufficient staking periods, correct? 

My understanding is that at the point of `consider_arrangment` the relevant Ursulas have already been sampled based on policy expiration date as it relates to staking duration. For the `/consider_arrangement` endpoint, Ursula returns a signature of the proposed arrangement - presumably to prove that they accepted the proposed arrangement in case there is some dispute  (?) - although I don't see any direct use of the signature anywhere other than verification that the signature return from `/consider_arrangement` is indeed from the Ursula. Only the list of Ursulas that accepted the arrangements are published to the blockchain. @KPrasch?

> I'm not sure if potential benefits (flexibility, shifting work/responsibility to Porter) are outweighing potential downsides (complexity, risk of misconfiguration, Porter DoS vector).

If verifying the signature is excessive and introducing some measure of trust - Porter does not have to perform the verification, instead the same response can be returned without Porter verifying signatures, leaving it only to the caller to do the verification.

**Comment by vepkenez** [comment]
> the same response can be returned without Porter verifying signatures, leaving it only to the caller to do the verification.

This seems like the way to go.  Porter shouldn't be responsible for that sort of thing.

**Comment by derekpierre** [comment]
After chatting with @piotr-roslaniec and @KPrasch, it seems that `/consider_arrangement` endpoint is nothing more than just an uptime check at this point, and not needed, especially for `nucypher-ts` since the `/get_ursulas` endpoint of Porter already:
1. Ensures that the ursulas to be sampled have sufficient staking duration for the proposed policy duration
2. Implicitly performs an uptime check of sampled ursulas before returning them by communicating with them to check their latest node information.

Therefore, for `nucypher-ts` purposes, a `/consider_arrangement` proxy Porter endpoint is not needed. 

Separately, @KPrasch is investigating the full removal of `/consider_arrangement` endpoint and `consider_arrangement()` method from the `nucypher` library.

**Comment by derekpierre** [comment]
Closing based on completion of discussion.
