### ISSUE TITLE
Better associated Schema/Field specifications for Control endpoints with their underlying python Objects

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher#2793]
Instead of having Schemas/Fields live in a separate area of the codebase from the objects they are associated with, potentially have them as part of the class itself with class methods.

Sample gist from @fjarri - https://gist.github.com/fjarri/35dfee392699eb67290c70a00ac86dbd.

Related to Porter (#2664) and character control endpoints.

**Comment by derekpierre** [comment]
@fjarri looked at your serialization gist. Some thoughts:
* It isn't clear to me that `Serializable` (`payload()/from_payload()`) is all that helpful outside of `BSONSerializable`. 
    * For `JSONSerializable`, the Fields should take objects for `_serialize`, and return objects (not bytes) from `_deserialize` - this was part of the change in #2768 - an example being TreasureMaps. This way we always end up with an object, and not some bytes representation that we then need to convert anyway.
     * For `BSSSerializable`, Couldn't the `bss_kwargs()` provide the actual specification of `PublicKey` instead of `bytes`? In which case the actual PublicKey object is returned and not bytes.
     * If `payload()/from_payload()` is only for `BSONSerializable` then we might as well just not have it, and let `bson()` define what the payload would look like and call `bson.dumps` on it directly - one good thing about this is that `bson()` and `from_bson()` get defined together in the implementer, and can be easily maintained to mirror each other.
 * For `BSSSerializable` any reason you wanted to have `bss_kwargs()` to specify kwargs, and not just have a method that instead defines the splitter to use eg.`bss_splitter(cls)` instead - less familiar with BSS so just curious.
 
Musings about the above thoughts are available here - https://gist.github.com/derekpierre/b38f51109ee0138c7f1c6b429954d184 - interested to get your take.

From a more high-level view, for classes defined in `nucypher` it would be simple to specify the fields/schemas in t how would the association of a Field and a Class work when the class is specified in a separate library, for example `PublicKey` or `CapsuleFrag` which are part of `umbral_adapter`? It wouldn't be defined in the class, so it would need to be defined somewhere in `nucypher`.

**Comment by fjarri** [comment]
> For JSONSerializable, the Fields should take objects for _serialize, and return objects (not bytes) from _deserialize

See the updated version: https://gist.github.com/fjarri/497220bd9d101d41c6a45879dcc54ea9 . Here the schemas will actually produce objects like they do now in `nucypher`. 

It can select between human-readable and binary serialization (kind of like `serde` does), but in order for it to work with BSS and support nesting, BSS must support stenciling (that is, turning the output of `schema.dump()` into a bytestring).

> For BSSSerializable, Couldn't the bss_kwargs() provide the actual specification of PublicKey instead of bytes? In which case the actual PublicKey object is returned and not bytes.

Since it will go through the schema, it will be the schema's job.

> For BSSSerializable any reason you wanted to have bss_kwargs() to specify kwargs, and not just have a method that instead defines the splitter to use eg.bss_splitter(cls) instead - less familiar with BSS so just curious.

Because I needed to do this in the base class:
```
        splitter = BytestringKwargifier(
            _receiver=lambda **payload: cls.from_payload(payload),
            **cls.bss_kwargs())
```
In the new version I'm ok with `BytestringKwargifier` producing a dictionary because it will be assembled into an object by the `marshmallow` schema.

> If payload()/from_payload() is only for BSONSerializable then we might as well just not have it

`from_payload()` is now used by everyone because it provides custom post-processing in the schema

---

In general, this starts to look like Rust's `serde` - it also uses a two-step technique. The first layer converts to an intermediate representation with simple types (`dict` in our case), the second layer deals with specific formats. 

I tried to use `marshmallow` as much as possible here, but I'm starting to feel that it's pretty limited and not very convenient to use in a custom fashion (e.g. it's hard to add a `post_load` to a `Scheme` object, you have to define it in the class).

**Comment by derekpierre** [comment]
Incomplete thoughts from our call this morning - https://gist.github.com/derekpierre/e4bfa084b03479d9a1afe7dbcdd2abd7.

Definitely agree that we need to look into how to make `post_load` not have to be redefined in Schema classes everywhere.

**Comment by fjarri** [comment]
Updated <https://gist.github.com/fjarri/497220bd9d101d41c6a45879dcc54ea9> with defaults for `from_payload()`/`payload()` and an automatic `post_load`. 

I don't think having `_HUMAN_READABLE` attribute in both `JSONSerializable` and `BSONSerializable` is a good idea seeing as how a class can have both as mixins. This can get confusing.
