### ISSUE TITLE
Rename MessageKit?

### ISSUE THREAD

**Issue by fjarri** [nucypher/nucypher#2818]
Following the current pattern in the protocol objects (`EncryptedKeyFrag`, `EncryptedTreasureMap`), would it make sense to rename `MessageKit` to `EncryptedMessage`? Or should we keep the original name since the users are already familiar with it?

**Comment by jMyles** [comment]
1) It basically depends whether we want to dismantle the "kit" notion (ie, a package of discrete items that are often shipped or saved together).
2) I know this is a topic of disagreement that's bigger than this issue, but, as you know, I don't really view the `<adjective><noun>` approach to class names as accurate in the first place (as adjectives are better used as attribute names), so naturally I don't think that `EncryptedMessage` is a superior class name.  That said, if it's more accurate, due to point 1 above, I'll accept it.

**Comment by fjarri** [comment]
> I don't really view the <adjective><noun> approach to class names as accurate in the first place

In this case, what would you go with for the other names using this pattern ([Encrypted/Authorized/Verified][TreasureMap/KeyFrag])?

**Comment by KPrasch** [comment]
> In this case, what would you go with for the other names using this pattern ([Encrypted/Authorized/Verified][TreasureMap/KeyFrag])?

Along the lines of this principal, it would be the naming scheme we had before: `KeyFrag.verified`, `Treasuremap.encrypted`, etc.

**Comment by KPrasch** [comment]
Personally, I think that `EncryptedMessage` or simply `Ciphertext` will be more intuitive for dApp developers.

**Comment by derekpierre** [comment]
> Personally, I think that EncryptedMessage or simply Ciphertext will be more intuitive for dApp developers.

I agree as well - they are sufficiently descriptive. In the immutable object world that we are working in, attributes don't help.

**Comment by derekpierre** [comment]
`MessageKit` has stuck around.
