### ISSUE TITLE
Question: integrate nucyher into Hyperledger Fabric

### ISSUE THREAD

**Issue by hlwone** [nucypher/nucypher#2839]
hi, @derekpierre from nucypher dev team. I am sorry to bother you. Nucypher is a wonderful project for data sharing and access control. Now it just has built-in ethereum support, I want to integrate nucyher into Hyperledger Fabric or any other enterprise blockchain. 

The following are some key points that I want to know about nucypher design.

- modularity  
Now NuCypher supports ethereum, if I extend it to support Fabric, is it enough just to extend code under nucypher/blockchain?
- staking working scope
Now though looking up docs, NuCypher has lots of staking design. I wanna to know whether this functionality is tightly coupled with nucypher node boarding. In other words, if I remove the staking design, how large its affect scope? which module will be affected? say, it will affect the nucypher node boarding process?
- remove staking in federated blockchain
 Just as the [nucypher whitepaper](https://github.com/nucypher/whitepaper/blob/master/whitepaper.pdf) said in `J. Private use of NuCypher`, it can be federated. If did't implement the staking contract, Nucypher token contract etc, the project still works?

could you give me some useful comments? any replies will be appreciated.

**Comment by derekpierre** [comment]
Hi there,

Of note: The NuCypher Network and Keep Network are currently upgrading the Threshold Network (https://threshold.network/), the first-ever crypto merge. 

Threshold Network will provide a suite of threshold cryptographic primitives and products from both NuCypher and KEEP: tBTCv2, proxy re-encryption, threshold signatures, distributed key generation, random beacon, with many more to come.

You can chat directly with us on the Threshold Discord, https://discord.gg/threshold, instead of via GitHub. I'm on there as well (`derek#2614`)

More information about that here:
- https://blog.threshold.network/what-is-threshold/
- https://blog.threshold.network/threshold-launch/

-- 

The NuCypher Network (https://github.com/nucypher/nucypher) is a decentralized network of nodes that provide threshold proxy re-encryption (PRE) as a service to dApps for secrets management and dynamic access control. There is some separation between the network of nodes and the underlying PRE scheme. The network is the decentralized service that provides PRE as a service, and therefore uses the blockchain for coordinating/distributing work, slashing nefarious nodes, censorship resistance, coordinating payments for service, trustlessness etc. all currently through ETH smart contracts. We are exploring supporting the use of the network PRE service on other chains such as polkadot, polygon, but it is very early. 

There is a federated version of the network that can be run without a blockchain and payments, but this originally served as a stepping stone and testing ground as we worked toward the decentralized/blockchain version. Federated code is not being as actively maintained as time has gone on since the public decentralized network was already launched. 

The underlying threshold PRE scheme used by nodes on the NuCypher Network is umbral (https://github.com/nucypher/umbral-doc/blob/master/umbral-doc.pdf), for which there is an initial python reference implementation called pyumbral (https://github.com/nucypher/pyumbral). As part of the expansion to other languages/platforms (js, web, mobile) we are working on a base rust implementation with bindings to other languages, rust-umbral (https://github.com/nucypher/rust-umbral). Both of these cryptographic libraries provide the threshold PRE cryptographic functionality without any need/reference/use of a blockchain.  

**It is worth noting that the aforementioned libraries are both AGPLv3 i.e. copyleft licenses.**

It would seem that the underlying threshold PRE cryptography libraries may be the area that you would be more interested in using with Hyperledger.

Happy to chat more if needed.

**Comment by hlwone** [comment]
got it. many thanks.

**Comment by derekpierre** [comment]
Closing this issue. This conversation can be continued on Discord.
