### ISSUE TITLE
What is the purpose to share a kfrag, which instead of a whole key with each Ursula?

### ISSUE THREAD

**Issue by hyerim-kim** [nucypher/nucypher#2845]
Hello 😃 

I've been interested in how to manage personal data safely, as a result, I found your project. 
So, I've been studying for some days, and I have a question about re-encryption key sharing. 
In other words, I'd like to know why a kfrag, which is a part of a whole re-encryption key,  must be shared with Ursulas.
I wonder which problem is occurred if a whole re-encryption key that instead of kfrag is shared each Ursula?
Please let me know documents, code or what else to help with the question if there are. 🙏 

Thank you for reading my question.

**Comment by derekpierre** [comment]
These questions are best asked in our [Discord](https://discord.gg/Threshold). You can ask any follow-up questions there in the `#proxy-re-encryption` channel

There are various risks at play as outlined in our [whitepaper](https://github.com/nucypher/whitepaper/blob/master/whitepaper.pdf) in "III. NETWORK SECURITY":

Specifically, there is a collusion risk to the security model. Here is an excerpt from the whitepaper:
> The first risk of this model is collusion between a miner and a reader of the data. If the miner gives the reader re-
    encryption keys for the data, the data can be decrypted at any time by the data reader, circumventing any conditional
    or time-based constraints. We counteract this threat in multiple ways: using split-key threshold re-encryption scheme
    Umbral [14] to decentralize trust between multiple miners, allowing recipients of the data to prove correctness or
    incorrectness of re-encryption to the other network by including verification protocol into Umbral, making the protocol
    reasonably pseudo-anonymous. In addition, we apply economic incentives for fair operation, described in Sec. VII.


Basically, the re-encryption key is split (threshold cryptography scheme) so that no single node controls the re-encryption key. The threshold of nodes (“m" in the "m-of-n” threshold) are needed to collude to reconstitute the re-encryption key (eg. for 3-of-5 threshold, 3 of the 5 nodes with re-encryption key shares need to collude). However, by itself, the re-encryption key doesn’t reveal any sensitive data other than allowing data to be re-encrypted from the data owner (Alice) to the recipient (Bob). However, if Bob then colludes with this threshold of Ursulas and obtains the re-encryption key, then Bob can circumvent the access control set forth by Alice i.e. continue to re-encrypt data for himself and decrypt it perhaps after Alice no longer wants to share data.

A prior talk that mentions some of the risks can be viewed [here](https://youtu.be/NeqeyDVse_E?t=824)

As a reference, an overview presentation on the NuCypher Network is available [here](https://www.youtube.com/watch?v=gOB6SojhrK4&ab_channel=NuCypher)
