### ISSUE TITLE
Renaming the PRE service in the context of Threshold 

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#2855]
These next few days may be the last chance to free ourselves of an abstruse and very unproductive acronym – I’m talking, of course, about P.R.E. One preface; this is not a suggestion to exhaustively rename PRE (nor ‘NuCypher’) in the character/contract code (besides in high-level documentation etc.). But our externally-facing _service_, as one of many hosted on the Threshold network, desperately needs a rebrand. A descriptive and confident name for advertising and discussing what these 300-odd nodes collectively offer.   At best, PRE tells prospective adopters nearly nothing about its value propositions, and at worst, it confuses and intimidates. As a bonus, it gives the off-putting impression we’re primarily interested in the academic side of cryptography. 

I’ve been thinking a bit about the use of the word ‘zero’ in crypto and security circles. Both worlds seem to be fine with the fact that the appended thing (-knowledge, -trust, etc.) isn’t truly zero. It depends on your definition of knowledge – if you define it as ‘data’, then it’s not zero. If you define zero-knowledge as not improving the verifiers ability to predict an answer, its arguably still not precisely zero.   Similarly for ‘zero-trust infrastructure/access’ – it’s absolutely not trustless in any sense, it more often involves increasing the frequency with which employee SSH credentials are refreshed, and authenticating every device regardless of locality.   So _zero_-x can in practice mean _lower_-x or _zero-unnecessary_-x. 

I’m sure some people will hate this suggestion (that’s ok, provided a stalemate doesn't leave us stuck with PRE), but it’s worth throwing out there:   **Zero-Trust Encryption**   

For example, FortKnoxster would use our service to encrypt data for a designated recipient, such that a specific (time-based, no oracle required) future condition triggers its immediate delivery, in a manner that burdens neither the user nor recipient with trusting FortKnoxster, at all. That latter value prop is so vital to the use case, it deserves to be front and center – i.e. possibly in the service name, or at least cognizable in the service name. 

 Although zero-trust security models are a well-defined enterprise concept and there is some risk of conflation, there is precious little out there when searching the entire phrase ‘zero-trust encryption’. With regard to 'encryption', we have an opportunity to claim territory (before someone else in the crypto space does) over this most fundamental and broadly-understood technique. Semantically reducing it to ‘re-‘encryption is too modest, and only describes one step in the sharing flow. 
 
 Alternatively, I also believe that incorporating a seemingly nebulous word like ‘privacy’ actually goes some way in describing our service. For example, Masterfile leverages our service to manage and safeguard decryption rights, as they pertain to certain digital assets. They are quite simply using a privacy-preservation service. I’m not trying to resuscitate PMP (Privacy Management Platform), but it honestly wasn’t a bad descriptor.  
 
Thinking further ahead, given that the vast majority of adopters will use PRE & PRE-DKG together, I think we should combine these two 'services' into one adopter-facing product with one adopter-facing name, tagline and set of educational resources – all of which reference the powers of AbioticAlice (on reflection, 'AbioticAlice' is another esoteric monstrosity).  The fact that PRE and PRE-DKG have differing service-side requirements and non-uniform node populations is almost irrelevant to the adopting developer.

**Comment by jMyles** [comment]
I can make the case this way:

What are `Bob's` concerns?  After all, Bob is the one benefitting from the presence of the data and the operations on the network causing it to be exclusively decryptable by him.

* "Proxy" - Bob only cares about this insofar as he needs network connectivity with the nodes which can deliver the `CFrags` to him.  This is the essence of our presence in a dapp.  You might say he only cares in the failure case ("wait, whom didn't I contact?  And why?  Are they down?  Are they behaving maliciously?  What's my next step to solve this and get the data I need?"), while in any success case he'd love to not think about the "Proxy" part of this at all.  This perhaps changes subtly in a "Bob pays" scenario.
* "Re" - Bob's concern here is even less important than with "Proxy".  With the warm orange glow of an activated capsule illuminating his smiling face, Bob is profoundly unconcerned about the hygiene stemming from where it has or hasn't been, because he holds the only secret material which can claim the prize inside.
* "Encryption" - here, Bob is very much concerned.  The cleartext must be visible to him and not to Eve.  This is his only motivation for using this system in the first place.

So, because "Proxy" and "Re" are unimportant to Bob, I agree with @arjunhassard that replacing them in favor of a different prefix to the word "Encryption" is viable.

**Comment by derekpierre** [comment]
TACo was the winner.
