### ISSUE TITLE
Stake validation criteria for participation in rituals

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#3109]
We need to discern what criteria we will use to validating a given stake to participate in rituals. For the moment, our current check in the Coordinator contract is that the authorized amount in the CBD app is > 0, but this is clearly insufficient. An immediate answer would be to set a min stake amount, but then we have the question of (1) how much, and (2) how to maintain consistency among Coordinators in different L2s; a viable solution for this would be to centralize this at the CBD app level, and reuse the L1->L2 sync mechanisms to update this downstream to L2s. 

But this issue goes a bit beyond this. Do we only want to check authorization amounts? Other stuff that we could check:
* Lock-up times: we haven't defined this for CBD, but we could reintroduce something similar to NuCypher stake locked duration. For instance, a staker could decide to lock-up their stake for 1 year (which could imply extra CBD rewards), and the lock-up info could be used to decide how to form the cohorts.
* Undelegation state: Check whether a stake is in the process of undelegating
* Longevity: Check for how long a stake has been authorized in the CBD app

**Comment by theref** [comment]
One aspect to keep in mind here is that all information on Polygon will be 20-30 mins behind L1

**Comment by arjunhassard** [comment]
From Barcelona in-person discussions:
- There's no point deviating from the global min. stake for the following reasons: 
   - We need as many stakers as possible to participate given more onerous deAuth delays (6-12 months)
   - We don't yet have any feedback or data on adopter preferences re: total economic security of a cohort (note global min. stake and 30 member cohort implies economic security of about $15k). 
   - Adopters can adjust cohort compositional requirements later, including raising the min. stake for incoming operators 
   - In absence of a mechanism that can reliably attribute and slash attempted collusion, collusion-resistance at this stage is more a case of logistical friction (e.g. approaching potential colluders without tipping off the network, working out which ciphertext is actually valuable), rather than a specific figure that 'competes' with bribes.

**Comment by arjunhassard** [comment]
Question: do we prioritize stakers with longer commitment times, for all cohorts? 
Pros – cohorts will likely require fewer replacements
Cons – cohorts will end up being comprised of the same nodes (less diversity)
