### ISSUE TITLE
Handle edge cases of m <= successes < n (eg, NotEnoughUrsulas resulting from nodes being unavailable)

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#3166]
Presently, we fail fast whenever a node in a desired cohort is unavailable.

Instead, let's wait and fail only if the resulting `successes < threshold` (as we do, for example, in the case where conditions aren't met).

**Comment by piotr-roslaniec** [comment]
In the precomputed Ferveo variant, we need `successes == threshold` to hold, otherwise share combination will result in a bad shared secret and the decryption will fail. In the simple variant, `success < threshold` is legal and will result in a correct shared secret, etc.,

After https://github.com/nucypher/ferveo/issues/36 is implemented, we should handle a case scenario where after precomputed variant fails (`success < threshold`) we transparently launch a smaller ritual with `threshold - success` participants using a simple variant and we perform a failover into a set of valid decryption shares.

**Comment by jMyles** [comment]
For some applications - web interfaces and chat bots, for example - this seems like it might be too slow.

We can allow the user to opt for starting with the simple variant, right?

**Comment by piotr-roslaniec** [comment]
> We can allow the user to opt for starting with the simple variant, right?

Yes, I don't see why not

If you're interested in performance, you may also want to consider that the share combination is slower on the client in the simple variant, between 10-150ms slower. In the precomputed variant it's essentially constant because this work is already performed on the server side (hence, the "precomputed" variant).  See https://github.com/nucypher/ferveo/pull/32 for details

**Comment by derekpierre** [comment]
The default ferveo variant used is now `Simple` (https://github.com/nucypher/nucypher/pull/3174) and indeed fail if `m` success cannot be achieved (https://github.com/nucypher/nucypher/blob/development/nucypher/network/decryption.py#L67). 

Closing this issue. If you disagree you can comment and reopen.
