### ISSUE TITLE
Malformed input sometimes results in full cohort returning 500 response

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#3225]
We had this issue with one of the Revealer attempts - I'll post a reproduction later.

**Comment by jMyles** [comment]
Spent the day hammering lynx with the discord bot to produce various 500 and other unexpected responses.  Two discoveries:


* Adhering conditions which specify conditions identical to those used in encrypt_for_dkg, but with a changed method name (this is for the  theconditionType of  contract obviously) causes a 500 repsonse rather than a 4xx.

* Perhaps more strangely: mucking the name in the functionAbi portion of the Lingo causes the node to actually check and complain that the method doesn't exist.  This suprised me because I expected the ciphertext to be invalid tout court.  What's that old expression?  Something something verification failed?

**Comment by derekpierre** [comment]
I think both of those boil down to the aad not being validated until after the conditions are evaluated and the decryption is actually attempted.

At the moment, the process for Ursula is:
1. Check that the signed ciphertext is authorized
2. Evaluate the condition
3. If the condition passes, derive decryption share using the `CiphertextHeader` and `aad`. This can fail if the aad is incorrect. (NOTE: the `aad` is comprised of the conditions and the public key as of #3194 )

Therefore, a modification of the condition associated with the ciphertext is currently not detected until 3) since the aad would be incorrect. 
Therefore:
1. Can we better detect the situation where the decryption share derivation failed because the aad is incorrect - maybe `ferveo`/`nucypher-core` already returns a specific exception for that case? cc @piotr-roslaniec.
2. The above improves the return code but not the overall situation. Is there a way to validate the aad without attempting to create a decryption share? If so, then the aad can be validated, then condition evaluated, then decryption share derived. cc @cygnusv , @piotr-roslaniec 


NOTE: modifying the existing condition associated with ciphertext is now trickier because we use the ThresholdMessageKit and ACP `nucypher-core` protocol objects and not just raw conditions with the ciphertext. However, it's not impossible once you know the format.

**Comment by piotr-roslaniec** [comment]
1. The [related, concrete error](https://github.com/nucypher/ferveo/blob/0a73aa38950c43fc059d210b43496a6cbaceb341/tpke/src/ciphertext.rs#L90-L90) is not propagated into a Python exception, and is [wrapped](https://github.com/nucypher/ferveo/blob/0a73aa38950c43fc059d210b43496a6cbaceb341/ferveo/src/bindings_python.rs#L38-L38) into an opaque [`ThresholdEncryptionError`](https://github.com/nucypher/ferveo/blob/0a73aa38950c43fc059d210b43496a6cbaceb341/ferveo/src/lib.rs#L32-L32) instead. We can improve on that by propagating a concrete Python exception, similar to what we already do with `ferveo` exceptions. 
2. [`tpke::ciphertext::CiphertextHeader` implements a `check`](https://github.com/nucypher/ferveo/blob/0a73aa38950c43fc059d210b43496a6cbaceb341/tpke/src/ciphertext.rs#L35-L37) method that tests the compatibility of a `ciphertext` against a given `aad`. It's currently not exposed but it should be a simple change in bindings.

**Comment by derekpierre** [comment]
Thanks for the info @piotr-roslaniec 👍  . 
* What would we specify as the `g1_inv` parameter for that check?
* I guess if we have that check in CiphertextHeader then we don't technically need the specific exception...although maybe still good to differentiate it.

**Comment by piotr-roslaniec** [comment]
`g1_inv` is a public DKG parameter, currently stored (hardcoded) in a DKG instance. If we don't have a DKG instance on hand in this flow, we could expose it as `PublicDkgParams` from bindings instead.

If we opt to expose `CiphertextHeader.check` from bindings, then IMHO it wouldn't make sense to throw an error since there since that method returns a `bool`. Currently, nothing about the `check` motivates throwing an exception - it's just a validation method. We could throw an error from `nucypher` instead, which is less obtrusive.

**Comment by derekpierre** [comment]
> `g1_inv` is a public DKG parameter, currently stored (hardcoded) in a DKG instance. If we don't have a DKG instance on hand in this flow, we could expose it as `PublicDkgParams` from bindings instead.

Ah! I think Ursula can create one or at least obtain the value from a helper method - https://github.com/nucypher/nucypher/blob/development/nucypher/crypto/ferveo/dkg.py#L28 (cc @KPrasch )

**Comment by piotr-roslaniec** [comment]
@derekpierre Ah, I see, I lost the plot there. I agree, adding a concrete error there would make sense.

And yes, the Ursula could use the existing method. Or we could consider it to be a workaround and add another convenience method that doesn't require ritual id to be known and so on.

**Comment by derekpierre** [comment]
Perhaps catching the generic `ThresholdDecryptionError` when getting decryption shares and returning the 400 Response with generic text is a simple enough fix for 7.0. This is probably a 5-line change.

The rest of the work aad validation etc can be done for 7.1.

wdyt @KPrasch, @jMyles ?

**Comment by arjunhassard** [comment]
Not reproduced
