### ISSUE TITLE
To which nodes does Alice initially PUT the TreasureMap?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#342]
Currently, we have Alice running `put_treasure_map_on_node` for *every* node about which she knows, *every* time she publishes a TreasureMap.  Let's have a calmer system.

**Comment by michwill** [comment]
That's a bit of an overkill, tbh. Options could be:
- put to `x` random nodes;
- put to `x` of known nodes selected with probability proportional to the stake (that's an overkill, imo);
- put to `x` of known nodes with largest stake (as the most trustworthy ones, so hopefully it will propagate);

IMO, good enough to start even with the first option

**Comment by cygnusv** [comment]
It seems that, with our current master (`50882a3eb6a796621956191e032bc963ef1abaab`), I'm experiencing this problem after successful granting. Policy creation, involving learning, and on-chain and off-chain operations, took approx 50 seconds, while publication of the treasure map took 4 minutes.

**Comment by cygnusv** [comment]
hey @jMyles, what about addressing this issue post-birdcage?

On this direction: how resilient is our network to TreasureMaps being stored only in a fraction of the nodes? or alternatively, assuming we still continue storing TreasureMaps in all nodes, would it be interesting to make it in such a way that Alice initially stores it only in a fraction of the nodes, and these nodes in turn will propagate it to the network? So that Alice doesn't have to push to all of them (even if we want all nodes to have the TMaps)
