### ISSUE TITLE
web3_clientVersion RPC calls are not cached properly

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#3450]
**Describe the Bug**
Since we're using simple_cache_middleware (see #3436 ), there should be only one call to web3_clientVersion for each web3 instance; same for eth_chainId. However, for some reason I see this is not the case for web3_clientVersion. For eth_chainId we additionally cache it at the nucypher ethereum client level, so that might be hiding the same problem.

**To Reproduce**
Use Alchemy or Infura dashboard to check usage of `web3_clientVersion`. You can even force it by refreshing the `/status` page, for some reason.

**Traceback or Screenshots (Optional)**
See in this infura dashboard how even after v7.2.0 started (around 08:00), the number of calls remain the same.
<img width="1348" alt="image" src="https://github.com/nucypher/nucypher/assets/2564234/23ab99dd-e681-46ac-8d42-f4d13e5955cd">

**System (please complete the following information):**
 - OS Version: ubuntu/docker
 - Nucypher Version: v7.2.0
 - Ethereum Node Version:  Infura/Alchemy

**Comment by cygnusv** [comment]
This issue is still happening, and affecting `eth_chainId` as well. Some nodes are reporting 40 requests of each per hour.

**Comment by cygnusv** [comment]
A possible lead: The origin of the call to `web3_clientVersion` when the `/status` page is retrieved, is that, when we get the operator balance, we try to get an existing `BlockchainInterface`, checking if the interface `is_connected()` along the way. This latter call does the following on the web3py side:
https://github.com/ethereum/web3.py/blob/e5350f8b657f5c53cd67285b1967c97ef8a97698/web3/providers/base.py#L113-L115

What I don't know is why this would bypass the simple cache middleware. Maybe because it's calling `JSONBaseProvider.make_request()` directly?

**Comment by derekpierre** [comment]
Really great find! 🎸 .

This makes sense now.

Typically requests go through a request manager - https://web3py.readthedocs.io/en/v6.20.2/internals.html#request-lifecycle, before going to the underlying provider.

Typical calls look like this (taken from stacktrace in #3551 )
```
File "/usr/local/lib/python3.12/site-packages/web3/manager.py", line 329, in request_blocking
	    response = self._make_request(method, params)
	  File "/usr/local/lib/python3.12/site-packages/web3/manager.py", line 213, in _make_request
	    return request_func(method, params)
```
i.e. going through the manager to make the request, that then uses the middleware etc. before then calling into the provider.

`is_connected()` in `EthereumClient` calls `w3.is_connected` which then goes directly to the underlying HTTPProvider, and does not go through the manager - https://github.com/ethereum/web3.py/blob/v6.20.1/web3/main.py#L404. 

That makes sense because something like the cache middleware would cause that connected check to be circumvented by returning a cached value instead of actually getting the result from the endpoint. 

So in this case, there is no caching for the `web3_clientVersion` call, because the call is actually made directly on the provider.
