### ISSUE TITLE
Configuration flexibility 

### ISSUE THREAD

**Issue by sammy007** [nucypher/nucypher#3471]
In some environments it would be extremely convenient if ursula will allow `host_port` and `rest_port` options to be set via command line arguments or even a path to an alternate config file. Maybe they are already exists, so pls update manual.

**Comment by sammy007** [comment]
Could just use:

```
volumes:
      - /share/nucypher/Primary.json:/root/.local/share/nucypher/ursula.json:ro
```

but normal command line params would add more flexibility for different use cases.

**Comment by derekpierre** [comment]
Users specify their own `rest_host` and `rest_port` via the configuration file. That file is generated during `nucypher ursula init` and IP resolution / override is done there.

The configuration file can be modified either via the command `nucypher ursula config ...` or by manually editing the file.

We don't really want to be in the habit of making it too easy for users to specify their own IP address and port, because they can easily misconfigure their node. Ideally, this is a one-time setting, and for more advanced users they can override it.
