### ISSUE TITLE
Decision: how we will initially implement javascript support?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#383]
@michwill reports intense hunger for JS support in the wild.

OK, so how do we initially give these people some of what they want?

1) Rewrite the entire project in JS.
2) Rewrite certain parts (presumably this includes things like umbral, policy, and agents but not things like the learning loop, network, and characters)
3) Provide a REST interface for `Alice.grant`, `Alice.generate_kfrags`, `Alice.create_policy`, `Bob.get_reencrypted_cfrags`, `Bob.join_policy`, `Bob.retrieve`.  People wishing to use NuCypher in this way will, I suppose, run a local node that exposes these things.

...and there are other ways.  But let's get the discussion started.

**Comment by michwill** [comment]
I propose the same path as Bitcoin and Ethereum did.
In both, initially there were full clients introduced (which could be mining or not) which can use a local key store. However, since they could accept signed transactions, it appeared possible to keep keys inaccessible to those clients (interfaced through an API), which made possible to create client-side web wallets. Of course, no "server-side" nodes written in javascript are adopted.

So, similarly to that, I propose these steps:
* Build an "Alice/Bob" client daemon which uses a local keystore. It will serve its API normally at localhost; Make possible to accept ready premade rekeys;
* Build jsUmbral so that the rekeys can be made in the browser;
* Then we may explore libp2p to check if it's possible to connect straight to the decentralized network from the browser.

**Comment by KPrasch** [comment]
Perhaps it's fair to close this now - since we have a reasonable agreed upon way forward by implementing RPC?

**Comment by afrancht** [comment]
I was wondering what was the decision?

**Comment by cygnusv** [comment]
We went for option 3 (creating a REST interface for characters) at that moment. But we may complement that with other approaches too.
