### ISSUE TITLE
Configurable Eagerness Setting for Learning Loop

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#404]

**Comment by jMyles** [comment]
Without a description, but with the configuration tag, I'm inclined to assume that this issue refers to the matter of *how to configure* eagerness of a given instance (or even a given Character), rather than the eagerness setting actually doing anything.

Since eagerness is now working in a way that's at least minimally mainnet viable as of #1451, but without any configuration knobs to the outside world, I'm inclined to leave this issue open until we have a proper `--lazy` flag or whatever the design decision is there.  Does that make sense?

**Comment by KPrasch** [comment]
Not yet done since it cannot be handled from worker configs.
