### ISSUE TITLE
The DHT is pulled.  What of TreasureMaps?

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#429]
@KPrasch and I made a quick (but good) decision to finally pull the DHT.  The choice was between either spending *another* day on workarounds for DHT wonkiness or pull it completely.

Since the DHT had already been so thoroughly deprecated as to relegate it only to facilitating propagation of TreasureMaps between Ursulas (a task which can be accomplished by other more robust means within a similar timeframe), we pulled it.

Be reminded that, until now, we have largely discussed a practice for Testnet wherein Alice simply hands the TreasureMap directly to Bob (upon granting).  

The DHT version of this scenario was fraught with real-world security concerns that were wont to raise their head even on testnet:

* It was possible for someone to upload a 10GB "TreasureMap", causing widespread frustration or even DoS.

* No particular authorization was required to place a TreasureMap on the DHT.  There was no reason to believe that it wasn't simply an arbitrary piece of data, and no reason to believe that each Policy was followed by exactly one TreasureMap.  

@tuxxy raises concerns here about exactly what we'll do now that we've pulled this piece of machinery.

I assert that it will be fairly straightforward to write a custom protocol for this in Twisted.  We might also consider implementing something standardized like Whisper.

And although this is a medium-sized undertaking, I don't think it was worth sinking more time into accommodating the DHT, nor is it even worth stressing about pre-testnet.

**Comment by cygnusv** [comment]
The DHT did seem like a juicy target for attacks. In fact, after explaining a little bit about NuCypher to some people, the DHT was the first concern raised. This is a good decision, in my opinion.

**Comment by michwill** [comment]
All good. It feels like all the decentralized projects start with DHT and mirate to something else.
One way to store could be using Swarm. If I remember correctly, Swarm is already used to store source code of smart contracts in a decentralized fashion. Although not blazingly fast, it can work well as a shared storage of treasure maps which we can always plug in

**Comment by jMyles** [comment]
Circling back around to this:  @szotov points out that, presently, the entire treasure map is gleanable by dint of examining the blockchain alone (of course, we are also well-advised to continually remind ourselves this is obviously a channel for collusion).  

For public testnet and initial mainnet release, though, do we want to derive a `TreasureMap` object from the blockchain?

**Comment by michwill** [comment]
Now thinking that the solution "app developer lets his Alice store the treasure wherever the f.. he wants" is probably the right one... Certainly better than every Ursula storing every treasure map

**Comment by jMyles** [comment]
From https://ptb.discordapp.com/channels/411401661714792449/411401661714792451/671049456694722580:

9:50 AM] dnunez: hey @jMyles, how do you see post-birdcage codebase to tackle 342? 
https://github.com/nucypher/nucypher/issues/342
[9:51 AM] dnunez: in the sense, how resilient is our network to TreasureMaps being stored only in a fraction of the nodes?
[9:53 AM] dnunez: or alternatively, assuming we still continue storing TreasureMaps in all nodes, would it be interesting to make it in such a way that Alice initially stores it only in a fraction of the nodes, and these nodes in turn will propagate it to the network? So that Alice doesn't have to push to all of them (even if we want all nodes to have the TMaps)
[9:54 AM] dnunez: (created a comment in 342 https://github.com/nucypher/nucypher/issues/342#issuecomment-578526333)
[9:55 AM] kprasch: My sense is that we want to stop storing TMaps on ursula all together - It's a freeloading a data sidechannel from the swarm but its a tough problem.  Is IPFS too optimistic?
[10:46 AM] michwill: IPFS is all right if there are nodes who pin some of the tmaps
[4:31 PM] jMyles: @dnunez, @kprasch, @michwill: I generally agree that it's a good idea not to be clunkily storing maps.  My reasoning is a little different: I don't think that it's per se a hard problem to allow only an Alice who has an active policy to store a small amount of free data per policy for the duration of that policy, but it might not be worth the extra engineering challenge to harden it, and ultimately, its a sub-par solution compared to a fully deterministic variant of Bob's Adventure.

So, if you're asking for the answer nearest to my heart, it's to (re?-)establish deterministic arrangements, using the methodology outlined in my forum post.  @maclane - did you copy those over to a google doc yet?
[4:37 PM] jMyles: (you know, 180 and all that :slight_smile:  https://github.com/nucypher/nucypher/issues/180 )
[4:37 PM] michwill: I think, a good way would be to switch to "app developer handles the tmaps side channel" format first, and then engineer a storage on top of that later, not hard-mixed with everything else
[4:37 PM] jMyles: yeah
[4:37 PM] jMyles: we can bolt-on a deterministic protocol after the fact
[4:40 PM] jMyles: If the forum can't be unearthed immediately, there's a discussion of this protocol here (which itself ammusingly starts with me fumbling to try to find it in the forum):

https://ptb.discordapp.com/channels/411401661714792449/412681039178366996/642469219610525715
[4:42 PM] jMyles: I'll copy the important part here for ease:

Alice and Bob use a static DH (or other shared secret) as a seed to the random sample select.  This makes a deterministic list of eligible nodes for any given block.  Alice traverses this list, and if for any reason she doesn't use one (for example, the node is down at that moment), she adds the index of that node (on the list) to her list of unused node indicies.  Then, once she has made Arrangements with n nodes, she commits the list of unused node indicies to the blockchain.

Then, Bob can make the exact same list, and when traversing it, he simply skips those nodes who index are in the unused list.

Boom, no more TreasureMap.

The only remaining question is how Bob determines the value of m.
[4:42 PM] jMyles: I really think this is the way to go unless somebody spots a terrible flaw.
[4:48 PM] michwill: What if Alice has multiple policies for Bob?
[4:49 PM] michwill: (also, this requires deterministic historic Ursulas to be easy to determine)
[5:25 PM] jMyles: 1) Multiple policies: the label can be added to the shared secret (or not, if AliceBob want to reuse the same cohort)

2) Everything that Bob needs to know about the state of the Ursulas can be learned by examining the blockchain up to a certain block, right?  And we've moved into blockchain-certain Bob anyway at this point, right?
[5:26 PM] michwill: 2) I'm not saying it's unsafe. I am saying that instead of storing the set of ursulas every day, we should have a method to determine the fleet at any point of time in the past - and that should be going out of Ethereum state rather than historic blocks
[5:27 PM] michwill: Or actually more than that
[5:27 PM] michwill: At any block in the past you should be able to determine a set of Ursulas for any policy duration. That's hard
[5:27 PM] michwill: That's, like, n_days ** 2 space
[5:28 PM] michwill: E.g. "who were the Ursulas supporting 34-day policies 11 days ago?"
[5:29 PM] michwill: (and what was their stake weight)
[5:29 PM] michwill: That's probably not impossible to record it in a packed way, but not exactly easy

**Comment by tuxxy** [comment]
Last Thursday, I dug into the nuances of the deterministic treasure map solution described in @jMyles post. While doing so, I found a method (I believe) of using bloom filters to replace the treasure map. The use of a bloom filter also improves UX in a few cases that I'll go over further down.

### Brief Introduction to Bloom Filters
A _bloom filter_ is a data structure that allows one to probabilistically test whether or not a given bitstring is a member of a set in a very compact and efficient manner. You are able to perform queries against the filter and receive a boolean output that a given bitstring is "probably in the set" or "definitely not in the set". This means it's possible for us to receive false positives (based on a probability you define), but _never_ a false negative. For more specific information on their construction, see the [Wikipedia page](https://en.wikipedia.org/wiki/Bloom_filter).

Some pseudocode might look like:
```
my_data_set = ["foo", "bar", "foobar"]
bloom_filter = BloomFilter(my_data_set, probability=0.000001)
```

And querying it would look like:
```
bloom_filter.check("foo")    // True, with a false positive probability of .000001%
bloom_filter.check("foobar") // True, with a false positive probability of .000001%
bloom_filter.check("barfoo") // False, definitely not in the set.
```

### Filter Map: Blooms Filters as a Treasure Map
When Alice creates a policy and grants access to Bob, they will sample a set of nodes and deliver each KFrag in the policy to a respective sampled node (an arrangement). After this process, Bob is able to gain access by delivering a Capsule to `m` Ursulas who have a KFrag from Alice. The list of all the `n` nodes in the Policy who have received a KFrag is referred to as a _Treasure Map_.

Presently, Bob is required to use this treasure map so that they are able to know who received a KFrag and is able to perform Proxy Re-Encryption services as pursuant to the policy Alice created. By replacing the treasure map with a serializable bloom filter, we are able to make something far more efficient and UX friendly.

Rather than serialize a large list of nodes who have all received arrangements, Alice can construct a bloom filter with the set of public keys of the nodes who have received arrangements. Serializing this bloom filter results in an extraordinarily small string, far smaller than the existing treasure map. Calculations to estimate this will be gone over later, but the size scales with `n` number of nodes and the false positive probability. The bloom filter will grow as more nodes are added to maintain the false positive probability defined in the setup.

When Bob needs to know which nodes on the network are capable of Proxy Re-Encryption services, they can iterate over their list of known nodes and query the bloom filter to check. Upon finding a probable candidate, Bob can then request Re-Encryption from that node. 
```
for node in known_nodes:
    probable_nodes = []
    if filter_map.check(node.pubkey):
        probable_nodes.append(node)
```
Performing an exhaustive search for all possible candidates in the bloom filter from a large set of known nodes is trivial and very efficient due to the probabilistic construction of the bloom filter. Thus, the small serialized _Filter Map_ can reliably replace the Treasure Map and allow Bob to determine which nodes Alice had arrangements with. In the above proposal, we eliminated the requirement for Bob to learn about the fleet network state during the time in which a policy was created by replacing the treasure map with a filter map. We also eliminate the need for deterministic sampling by assuming Alice shares the filter map via side channel. 

### Improving the 'Filter Map' and Open Questions
There are a few potential areas for improvement upon implementing a filter map. First, the filter map doesn't require the whole public key of an Ursula to be placed in it. We can use a large-enough substring of it to further improve space efficiency in the bloom filter and reduce the size of a serialized filter map.

Second, deterministic sampling potentially offers a significant UX gain by eliminating the need for a side channel. However, there is an open question in how Bob will recover the set of `n` nodes for their policy. If this set of nodes is placed into a filter map, it must still be transported to Bob via a sidechannel, thus eliminating any opportunities for improvement. If there was a method of sampling that only required the knowledge of Alice and/or Bob's metadata (keys, etc), then there's a possibility of further improving on this part. It's recommended that deterministic sampling be fully explored in conjunction with filter maps despite this lackluster improvement as future developments could be far more exciting.

Third, the a filter map creates the opportunity for NuCypher "magnet links". Due to the filter map's small size, it's possible to reduce the sidechannel to a simple copy/paste into a potential client or file very similar to torrents. This would greatly enhance the NuCypher UX and make it comfortable to those who are already familiar with torrents.

**Comment by cygnusv** [comment]
A couple of comments:
* Use staker addresses rather than public keys (20 bytes vs 33 bytes). Or even better, if we accept a blockchainy Bob you can even use the staker index in `StakingEscrow` which is way, way shorter (1 or 2 bytes per node).
* You're forgetting about arrangements IDs. The TreasureMap is actually a list of `(ursula_i, arrangement_i)`, where `ursula_i` is an Ursula ID (e.g, staker address) and `arrangement_i` is currently a 32-bytes random identifier. Solving #180 with some deterministic arrangement ID is a prerequisite of any attempt at producing a more compact representation for TreasureMaps.
