### ISSUE TITLE
Facilitate Ursula connectivity behind firewall / NAT.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#486]
Presently, Ursula doesn't trivially work behind a firewall or NAT because her REST server needs to run on a discrete, public-facing port.

The promises and dreams of IPv6 notwithstanding, it's reasonably plausible to run this service from behind a firewall, in the image of what eg BitTorrent does.  To jog your thinking on this, see: https://superuser.com/questions/104462/how-does-bittorrent-work-with-only-outbound-connections

This is actually fairly easy for the learning loop, but somewhat more difficult for the more "RESTy" features (ie, policy management and re-encryption).

For example:

Imagine that we now have two categories of Ursula connectivity: public-facing and NAT'd.  

If Alice wants to connect to a specific sampled Ursula, and that Ursula is NAT'd, then how does Alice connect?  If the answer is something like, "well she connects to a `known_node` which is public-facing", then haven't we effectively re-centralized the network (and perhaps created a free-rider problem)?

There are of course a number of different "NAT traversal" techniques (elucidated for example [here](https://en.wikipedia.org/wiki/NAT_traversal#Techniques)).  But are any of these a perfect fit for us?

What shall we do?

**Comment by cygnusv** [comment]
Painfully slow, but [Tor hidden services](https://www.torproject.org/docs/onion-services.html.en) solve this problem by using intermediate servers receiving outbound connections from the endpoints. 

Some cool features of using off-the-shelf Tor hidden services for Ursulas:
- Instead of IPs, Ursulas would have onion addresses (e.g., "`vdskjfnvosaeugrfhsd.onion`"). IPs remain
- Firewall and NAT issues are solved since Ursula only needs outbound connections
- Rendezvouz points, which are the intermediate servers, are already there to be used, courtesy of Tor.
- Anonymous communications, of course.

**Comment by derekpierre** [comment]
Can we close this?

**Comment by derekpierre** [comment]
Currently, node operators need to know what they are doing regarding network configuration, static IPs etc. at the moment. Down the road we may revisit.
