### ISSUE TITLE
beachhead notebook : example confused by single-threaded data sharing

### ISSUE THREAD

**Issue by haroldcarr** [nucypher/nucypher#505]
https://github.com/nucypher/nucypher/blob/master/doc/NuCypher_Beachhead.ipynb

The example is a single thread that shares data (like Alice's signing public key, the label, the message kit).
The data sharing is particularly confusing during retrieval by Bob:

```
datasource_as_understood_by_bob = DataSource.from_public_keys(
        policy_public_key=policy.public_key,
        datasource_public_key=data_source_public_key,
        label=label
    )
delivered_cleartext = BOB.retrieve(message_kit=message_kit,
                                       data_source=datasource_as_understood_by_bob,
                                       alice_pubkey_sig=alices_pubkey_saved_for_posterity)
```
but many of these argument values (e.g., `message_kit`) would have been created by a different process/computer.

The example would be better if split into 4 processes:
- Alice
- a delegate that creates data on Alice's behalf
- Bob
- nucypher

The main question I have now is:  how does Bob provide a `message_kit` if he is a separate process?

**Comment by cygnusv** [comment]
Hi @haroldcarr!
You're right about the limitations of showing this in a single script or notebook. In reality there are four processes, as you noted. It's important to note that the only actions that have to be sequential from these processes or actors are the following:

1. Alice creates a policy public key
2a. The Data Source encrypts data under this public key, producing this way a `MessageKit`
2b. Alice grants access to Bob for this policy
3. Bob retrieves a ciphertext he can decrypt via the NuCypher network

Steps 2a and 2b don't have to be in that order, but they have to be in between 1 and 3. 

The message kit is expected to be presented to Bob via a side-channel, i.e., it's outside of the scope of NuCypher. For example, after the Data Source creates pair of ciphertext and capsule under some Alice's policy key, he can upload them to S3, IPFS, or whatever storage medium so that Bob can access it. Of course, only with this ciphertext and capsule alone, Bob cannot read the data as he needs access granted by Alice and enforced by the NuCypher network. 

Finally, a small clarification: the Data Source does not only represents an entity that creates data on Alice's behalf. It can be also any entity that wishes to produce data for Alice to manage as she sees fit, that is, either she consumes that data by herself, or she delegates it to some Bob.

**Comment by cygnusv** [comment]
Consequently with the closure of #418, I think this can be closed and the notebook should be either marked as deprecated or directly removed. We don't have the resources to keep it updated.

**Comment by haroldcarr** [comment]
agreed
