### ISSUE TITLE
Buckets.  We need Buckets.

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#567]
Currently, we have just a single bucket for nodes - `known_nodes`. 

But we need to bucket them separately.  Nodes that are palpably offline don't belong in this bucket.  Nor do those whose metadata is out of date.  Or probably even those who have a known-but-out-of-date fleet state.

**Comment by KPrasch** [comment]
Guess I better roll up my sleeves!  I'd like to work on this Issue this week since I anticipate it will need several iterations for a minimum viable solution.

**Comment by cygnusv** [comment]
Moved to Mainnet month 1 milestone
```
dnunez Today at 5:36 PM
what if we go to mainnet without buckets? @jMyles @kprasch I don't immediately see it's urgent, but I admit I don't fully understand the extend os this issue
jMyles Today at 5:37 PM
@dnunez: It's an option worth considering.  It can be introduced later.  It makes me a little uncomfortable, but it won't be a complete disaster.
```

**Comment by KPrasch** [comment]
Finally I'm going to close this issue since it has grown to be too broad and is partially fixed since nodes now track a verification state of each peer effectively creating two "buckets".  Any additional buckets represent enhancements and optimizations for stability/performance/accuracy.  Related to #355
