### ISSUE TITLE
Ursula seems to pause for long periods

### ISSUE THREAD

**Issue by jMyles** [nucypher/nucypher#598]
@cygnusv noticed a strange hanging behavior in the CLI today.  

What else do we know about this?

**Comment by KPrasch** [comment]
Thanks for opening this - Here's some of what I know:

- `nucypher ursula run` will hang on startup for long periods of time (2-60 seconds has been observed)
- Logs indicate the blocking occurs at the same time as seednode learning, then (mostly) resolves it self afterwards
- The user must be acting quickly to notice the stalling in many cases
- The Issue is not always reproducible; At home I cannot reliably recreate this behaviour
