### ISSUE TITLE
Bring the Exceptions back home

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#666]
Something in the codebase (perhaps `twisted`?) is suppressing valuable exceptions. For example, behind the 500 status code when the `/consider_arrangement` REST entrypoint was called, there was a `sqlite3.OperationalError` (#662), which I found after surrounding the offending line with a `try...except`.

**Comment by tuxxy** [comment]
I have to say, this made working on revoke exceptionally difficult.

**Comment by jMyles** [comment]
I haven't really encountered this (or have I, and I'm just not thinking clearly about it?).

How can I reproduce this?  Is there a test that shows it?

**Comment by cygnusv** [comment]
1. Checkout `cygnusv/devils-issue`
2. Run `nucypher ursula run --dev --debug --federated-only` in one terminal
3. Run `python examples/heartbeat_demo/alicia.py 127.0.0.1:10151` in another. This will fail.

The node returns a `500` for the `/consider_arrangement` entrypoint, and no other information is known about the error, but there's a `sqlite3.OperationalError` occurring in [L.112 of the keystore](https://github.com/cygnusv/nucypher/blob/devils-issue/nucypher/keystore/keystore.py#L112) which is suppressed for an unknown reason. If you surround that line with a `try ... except` you can catch it.

**Comment by jMyles** [comment]
:imp:

**Comment by jMyles** [comment]
OK, I have my head wrapper at least partly around the problem.  I don't think that's it's the same as the one described in your SO link, @cygnusv (see [Discord discussion here](https://discordapp.com/channels/411401661714792449/411401661714792451/536219397992349696)).

**What's happening is actually ordinary, intended behavior, strangely enough.**  Ask yourself this question: what do you *want* to happen here?  Here are some options:

1. Ursula raises the exception to the top of the process, causing it to exit with an unhandled (in this case) `OperationalError`.  This is obviously a non-starter, as any bug will cause a node to terminal pending human intervention (or worse, cause a systemd hammer).
2. Ursula returns a 500, discards the request, and clears the thread to listen for a subsequent request.  This is what happens now - in `apistar.server.app.__call__`, to be specific.  I think that the reason I haven't noticed this issue is that I have a breakpoint in the `except` clause of this method, so it just hadn't yet occurred to me that anything was being silenced. 
3. Ursula returns a 500, logs a traceback if available, and, if a "debug" flag is set, displays an error page that includes some traceback information and other information about the runtime environment.

Now, I bet you are saying "Well, I want option 3 - obviously - isn't that how things work?"  And I think that the reason you're thinking that is that *Django* and *Flask* (ie, the application) do those things.  But generally, web containers like hendrix / gunicorn / don't have this facility.  And nucypher (our application), presently, doesn't do those things.

### But what about apistar?  Isn't this why we pay apistar the big bucks?

As best I can tell from [the docs](https://docs.apistar.com/) APIStar expects you to roll your own solution for handling this and is actively moving away from this sort of "system" role in favor of more of positioning itself as a "toolkit".  It previously provided an Event Hook for this purpose, but, as best I can tell, that seems to have been removed amidst highly differing expectations of behavior across the user base.  

*I assert that this is another piece in the growing body of evidence that APIStar is not a good fit for this project - it adds very little, but doesn't give us batteries that we've unknowingly come to expect.*

So, how to fix this?  It's really not that hard, but we have to pick a path.

### Options
1. Wrap `ProxyRestRoutes` in such a way that examines return values from its methods and executes special logic if the status code is >= 500.  Ugly, hacky, but explicit and obvious.  We'll have to do it again for the RPC.
2. Add this functionality (optionally) to `HendrixWSGIResponse`.  This is another acknowledgement that hendrix lives with one foot in a sort of in-between zone between container and application, and I'm personally fine with that.  @KPrasch, how does this sit with you?
3. Switch to Flask.  I know @tuxxy likes Flask (though, as I've said before, I find this somewhat surprising, as its over-the-top OOP nature seems to go against some of his normal sensibilities), and I do too.  This seems like a relatively easy option.
4. MonkeyPatch APIStar and add logging in the appropriate areas.  I'd only consider this if this were a hail-mary approach on an otherwise broken production environment.
5. Open a PullRequest to APIStar in an effort to introduce "Django-style" error handling.  Highly unlikely to prevail in my assessment.

Of course numbers 1, 2, and 3 can be done in concert; each has its own set of discrete benefits and tradeoffs.

### But wait - this must be a fairly universal problem - what are others doing about it?
I'm mostly inclined to defer to @KPrasch on this, as I think he has his finger more on the pulse of python web tooling than I do, but I suspect that this is actually one of the things that is either keeping people tightly bound to Django or fleeing all the way to Node.  :man_shrugging: 

Ultimately, if we want flexible error handling that works across our three network domains (learning, policy service, and character control (what we've been calling "the RPC")), then I think that adding some tooling to hendrix makes good sense.  I'm confident that I can have this done inside a day.

**Comment by KPrasch** [comment]
> ...APIStar is not a good fit for this project... 

Agreed - In my mind, API start is *no longer* a good fit for NuCypher both due to their re-positioning as a toolkit, as well as our refined sense of requirements for web servers and services.  In fact, since we started using APIStar, The "web server" has been deprecated from the project, and we have been pinned to version `0.5.41`.

### Options I've considered since reading @jMyles's proposed options:

  - A. Use API Star error hooks from legacy version and / or `debug` flag were appropriate  ... (do I need to say more?)

  - B. Switch to a fast and modern ASGI framework: [Starlette](https://github.com/encode/starlette) + Uvicorn (see impressive performace [chart](https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=fortune&l=zijzen-1)).

  - C. Add this functionality to `HendrixWSGIResponse`.

I think modifying `HendrixWSGIResponse`  represents *a part* of the changes needed to maintain the project as it grows older, not to mention *hendrix is already implemented in nucypher*.

Despite that, at I sit now I'm most favouring option B -  (See the error handling approach [used by Starlette here]
(https://www.starlette.io/exceptions/)). 

Options B and C seem acceptable but I'll need to think this over a bit more.  Ultimately, there needs to be some facility for handling server exceptions or else we are dooming everyone to terrible debugging experiences, mysterious errors, and unwanted downtime.

**Comment by michwill** [comment]
Agreed. And since the swap wasn't all that difficult (wow, you did it in a day!), we can swap to some other framework if we think it's good.
The one I looked at some day was Falcon, and it seems pretty alive. But I'd say, indeed, let's take Flask for now and move forward

**Comment by KPrasch** [comment]
@jMyles - Is this still open?
