### ISSUE TITLE
`encrypting` flag in NucypherKeyring seems redundant

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#668]
All the characters that make use of the keyring (i.e., Ursula, Alice and potentially Bob) have `DecryptingPower`. Hence, it seems that the option `encrypting=False` is not needed. I think we can safely get rid of that flag. 

I already started some work in that direction, let me know if I should continue.

**Comment by KPrasch** [comment]
Yea - This sounds OK.  The only hesitation I've had up to this point is the uncertainty around "repairing" a system installation, wherein the user will need to generate, say, only a TLS private key.

**Comment by cygnusv** [comment]
The NuCypher keyring has to handle the generation and protection of the following keys. 
- **Ursula**: signing, encryption, tls, wallet
- **Alice**: signing, encryption, delegation, (wallet?)
- **Bob**: signing, encryption, (wallet?)

I think we can redesign a little bit how is this organized inside the keyring and how's the API. There's an open PR, #699. So, what's the general opinion on this issue? 

1) Always create signing and encryption keys, hence removing the `encrypting` flag. @KPrasch mentioned previously some concerns for this case.
2) Add a new flag `signing` for creating signing keys. This seems redundant to me, but if the previous concern is strong enough, we could go this way.

3) Add a new flag `delegating` to consider the case of Alice, who is different to the rest in that she needs to establish a delegating secret. Currently, we're generating such secret for everyone with `encrypting=True` (which is always).

It seems to me that (3) is necessary either way, but I'm not so sure regarding (1) and (2). I'd prefer your input before continuing with this.

**Comment by KPrasch** [comment]
Yeah - Good scoping here.  I agree that it's time to revisit the keyring, but I stand by my original perception: It looks you have accurately enumerated the *keyring initialization* procedure for each character, however, there are other situations for  keyring usage: key rotation, generating a spare key, application update, system installation repair, etc.  My "concern" is that we will build the keyring logic too tightly, and specialized for initialization instead of life-cycle leading to technical debt.

**Comment by cygnusv** [comment]
Fair enough. That means that a combination of options 2 and 3 gives us a lot of flexibility in the scenarios you describe.

**Comment by cygnusv** [comment]
Closed by #2701
