### ISSUE TITLE
`addAffineJacobian` does not output 0 efficiently

### ISSUE THREAD

**Issue by incertia** [nucypher/nucypher#748]
we have the following code

```
    function addAffineJacobian(
    	uint[2] memory P,
    	uint[2] memory Q
    ) internal pure returns (uint[3] memory R) {
        uint256 p = fieldOrder;
        uint256 a   = P[0];
        uint256 c   = P[1];
        uint256 t0  = Q[0];
        uint256 t1  = Q[1];

        if ((a == t0) && (c == t1)){
            return doubleJacobian([a, c, 1]);
        }
        uint256 d = addmod(t1, p-c, p); // d = t1 - c
        uint256 b = addmod(t0, p-a, p); // b = t0 - a
        uint256 e = mulmod(b, b, p); // e = b^2
        uint256 f = mulmod(e, b, p);  // f = b^3
        uint256 g = mulmod(a, e, p);
        R[0] = addmod(mulmod(d, d, p), p-addmod(mulmod(2, g, p), f, p), p);
        R[1] = addmod(mulmod(d, addmod(g, p-R[0], p), p), p-mulmod(c, f, p), p);
        R[2] = b;
    }
```

let us expand `R` with `t0 = a` and `t1 = -c`. clearly we have `b = 0 ==> R[2] = 0`. as for `R[0]`, we have `e = f = g = 0` so `R[0] = d^2 = (-2c)^2 = 4c^2`. carrying on with `R[1]`, we have `R[1] = d * (g - R[0]) - c * f = (-2c) * (-(-2c)^2) - 0 = -2c * -4c^2 = 8c^3`. in particular, `(4c^2, 8c^3, 0)` is a valid point for `0` but its calculation can be greatly simplified by just returning `(1, 1, 0)` for this case.

**Comment by cygnusv** [comment]
Thanks for the finding! Indeed, this is not outputting 0 efficiently, but I don't think that it will be too frequent to use this function to add a point `P` to its opposite `-P`. And in any case, since the computation of `P + (-P)` is correct, I think it's worth the extra cost for this particular case, rather than incurring in an additional check always. This is different to the case when this function is used to add `P` to itself (i.e., doubling), since in this case, the formulas don't work and the result is incorrect, so there's no way around that particular check.
