### ISSUE TITLE
`doubleJacobian` does not output 0 efficiently

### ISSUE THREAD

**Issue by incertia** [nucypher/nucypher#750]
similar to #748 , if you check for `P[1] == 0`, you can immediately output `(1, 1, 0)` instead of going through an arduous computation to arrive at 0.

**Comment by cygnusv** [comment]
Can you clarify this? In `doubleJacobian` we do the following:
```
function doubleJacobian(uint[3] memory P) internal pure returns (uint[3] memory Q) {
        uint256 z = P[2];
        if (z == 0)
            return;
        ...
    }
```
I think the check you mention is already there, since if `P` is 0 (i.e., `P[2] == 0`), the point `Q = (0, 0, 0)` is returned. I'm aware that technically `(0, 0, 0)` is not a valid representation of the point-at-infinity, but in the code, we only check whether the z coordinate is 0 for that, so it doesn't matter (and it's cheaper!).

**Comment by incertia** [comment]
Recall that if `(x, y, z)` is a point on the curve then its additive inverse is `(x, -y, z)`, so when this `y` coordinate is 0, doubling should also produce the point at infinity. Similar to your response to #748, this may be a rare case you might choose to ignore.

Additionally, if you are absolutely certain that every place that potentially adds 0 does the correct check, then it should be fine, but it should not be that much more expensive to just construct a correct value just to be on the safe side. I will verify this today.
