### ISSUE TITLE
Introduce FAQ into Documentation

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#829]
#### Starter Ideas

 - Advantages of NuCypher over traditional PKI
 - Why not use ETH keys as Umbral keys?

**Comment by arjunhassard** [comment]
@KPrasch All for this. I recommend separating answers into distinct categories: 

1) I'm unsure if NC brings enough value to my users to be worth the cost/trouble.
E.g. _Why can't I just 're-encrypt' sym keys in the client?_
E.g. _Why is useful for entities other than the data owner to encrypt on their behalf?_
E.g. _Why can't I just use a smart contract to enforce access control?_
This section is basically: https://github.com/nucypher/wiki/wiki/NuCypher:-Why-should-I-care%3F

2) I'm unsure if it will be profitable/worthwhile to become a network node. 
E.g. _How do I maximise the inflation-based rewards I will receive?_
E.g. _How computationally expensive is performing re-encryptions likely to be?_

3) I need help integrating NC access control into my application.  
E.g. _Why can't my users re-use their ETH wallet pk/sk when creating a sharing policy?_ 
E.g. _How do I integrate NuCypher if my application is not written in Python?_

4) I need help spinning up a node. 
E.g. _How do I get NU tokens?_
E.g. _How do I see my node's status and other info?_

1 & 2 should be front and centre, since 3 & 4 are only relevant if you have progressed past the uncertainty and are willing to commit time and energy to understanding our system.

**Comment by KPrasch** [comment]
With a little modification ad addition I suggest the following questions (Preferably as bullet points in rendered docs with bold questions and italic answers, but I'll leave numbering here for reference):

1. How do I know if NuCypher is a good fit for my use case?
2. How is NuCypher different from more traditional public key infrastructure (PKI)?
3. Will it be profitable/worthwhile run a network node?
4. How can I get help integrating NuCypher into my application?
5. I need help setting up or operating up a node!
6. How/Where can I acquire tokens?
7. How can I get started contributing to NuCypher?

**Comment by KPrasch** [comment]
Anyone have thoughts on this? I'd like to start this document very soon.

**Comment by derekpierre** [comment]
Related to #1639 .

**Comment by KPrasch** [comment]
FAQ has been introduced, and iterated on as of #1639, #1728, #1781, #1806...
