### ISSUE TITLE
Provide predefined set of options for m-of-n

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher#853]
We can define a set of ~3 default configurations of m-of-n, considering also the cost of deploying such policies. This can be similar in essence to how metamask handles gas in their UI.

Some reference discussion:

https://discordapp.com/channels/411401661714792449/552911017642950656/556527448192450580

(Thanks @day-aaron)

**Comment by KPrasch** [comment]
See related #984

**Comment by KPrasch** [comment]
@cygnusv - Any ideas on how to name these presets?

**Comment by cygnusv** [comment]
Maybe move this to `nucypher-ts`. @piotr-roslaniec WDYT?

**Comment by piotr-roslaniec** [comment]
For `nucypher-ts`, there are no default settings at the moment. The default values in `nucypher-ts-demo` are provided by the web app itself (2 of 3). 

I think the least we could do is add config examples to documentation together with some explanation. That should give users some intuition about them. 

Because in TS default parameters are optional, defaults in `nucypher-ts` could be implemented like so:
```
const {m, n} = Policy.defaults()
```

Maybe having a "policy simulator" gadget would also be helpful in understanding how m-of-n settings impact the policy cost, but that seems like a different endeavor.

**Comment by cygnusv** [comment]
Not in the `nucypher` scope anymore. Superseded by https://github.com/nucypher/tdec/issues/51
